### ISSUE TITLE
Hit an error in opening ipfs-desktop

### ISSUE THREAD

**Issue by Maxzong** [ipfs-shipyard/ipfs-desktop#683] opened 2018-11-08 20:05 UTC
<img width="425" alt="screen shot 2018-11-08 at 8 27 16 pm" src="https://user-images.githubusercontent.com/17782773/48224071-b0495280-e3d3-11e8-8349-4d98cdaba3c4.png">

Yesterday, I upgraded ipfs version from 0.4.15 to 0.4.18, according to the manual of IPFS- Update, finished migration job before that. Everything seemed fine before I restarted my mac this morning. There was an error msg popped up for some times before ipfs-desktop quit by itself. The msg list below（the screenshot picture is attached ）

"Some unexpected error occurred and we couldn't handle it. Please check /Users/maxzong/Library/Application Support/ipfs-desktop/logs/error.log for the latest logs and open an issue on https://github.com/ipfs-shipyard/ipfs-desktop/issues."

Ok, after viewed the error.log  lies in /Users/maxzong/Library/Application Support/ipfs-desktop/logs/,  I got the key information lists below:

"Your programs version (6) is lower than your repos (7).\nPlease update ipfs to a version that supports the existing repo, or run\na migration in reverse.\n\nSee https://github.com/ipfs/fs-repo-migrations/blob/master/run.md for details"

Does it mean that the latest ipfs-desktop application isn't adapting to repo's version? Repo is the newest I downloaded and installed yesterday, it's the latest version following the steps in "Running Repo Migrations"

Could anybody gimme a hand to solve it? thx a lot

**Comment by Stebalien** [comment] 2018-11-08 20:58
@hacdias is this a js-ipfs/go-ipfs interop issue?

**Comment by hacdias** [comment] 2018-11-09 19:35
Probably the latest binary of IPFS Desktop uses an older version of IPFS thus the error. We're now working on a newer, simpler version and hopefully those issues will be addressed easily.

**Comment by hacdias** [comment] 2018-11-14 19:34
Closing as we know what the problem is.

**Closed by hacdias** 2018-11-14 19:34 UTC
