### ISSUE TITLE
MacOS can no longer check for updates

### ISSUE THREAD

**Issue by momack2** [ipfs-shipyard/ipfs-desktop#1487] opened 2020-05-04 04:46 UTC
- OS: MacOS
 - Version of IPFS Desktop 0.10.4

**Describe the bug**
Cannot connect to internet to check for latest version since 0.5 release

**To Reproduce**
1. about
2. check for updates
3. see "could not check for updates, not connected to the internet"

**Expected behavior**
my node finds the new version and installs it

**Additional context**
On Tuesday morning PST I was able to check for updates (and was told my node was up to date). As of Wednesday PST I was no longer able to check for updates.

Logs:
[combined.log](https://github.com/ipfs-shipyard/ipfs-desktop/files/4572800/combined.log)
[error.log](https://github.com/ipfs-shipyard/ipfs-desktop/files/4572803/error.log)

**Comment by lidel** [comment] 2020-05-04 11:04
Unfortunately logs do not tell us much:

```
2020-05-04T04:44:09.180Z info: [updater] update available. download started
2020-05-04T04:44:39.197Z error: [updater] Error: Request timed out
2020-05-04T04:44:39.198Z error: [updater] Error: Request timed out
```


it looks similar to this upstream issue:  https://github.com/electron-userland/electron-builder/issues/4744 which seems to be why people hardcoded older version v4.2.2: https://github.com/unipept/unipept-desktop/issues/28#issuecomment-595781591

-----

I did some initial analysis and:

ipfs-desktop v0.10.4 is using electron-updater v4.2.4
ipfs-desktop v0.11.1 is using electron-updater v4.3.1 (recent bump: https://github.com/ipfs-shipyard/ipfs-desktop/pull/1462)
ipfs-desktop v0.11.2 is using electron-updater v4.3.1 

@rafaelramalho19 are you able to do some smoke-tests of update mechanism on Mac/Windows?
1. Do a fresh install of [v0.10.4](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.10.4) and reproduce the issue (menu→about→check for updates)? 
2. Check if the problem is still present in [v0.11.1](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.11.1) by doing the same?

**Comment by rafaelramalho19** [comment] 2020-05-04 11:41
Smoke test on 0.10.4 is breaking:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24696635/80961545-0f3e2b00-8e03-11ea-91f1-27d0d714adfa.gif)

Same for 0.11.1, but appears to be a different "alert": 

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/24696635/80962226-8a541100-8e04-11ea-9b7b-3d68d5fb1b79.gif)

**Comment by rafaelramalho19** [comment] 2020-05-04 11:51
After further investigation it looks like the updater only takes into account the electron version:
![image](https://user-images.githubusercontent.com/24696635/80962926-e4a1a180-8e05-11ea-8050-6d1bdf2f0028.png)

* (8.2.4 is the electron version, 0.11.2 is the latest app version)


We should fix this ASAP by separating the APP updates from electron's version.

**Comment by rafaelramalho19** [comment] 2020-05-04 12:38
Upon further investigation and some wizarding debugging, I found that error is thrown whenever the auto-updater is trying to update a non-signed app.

@momack2 can you confirm that you were using a version built from the source code (or without signing) instead of the one available from [releases](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.10.4)?

**Comment by autonome** [comment] 2020-05-04 14:08
Non-signed or non-notarized?

**Comment by lidel** [comment] 2020-05-04 14:27
It is both, but here we suspect signing: 
Non-signed == built from sources locally instead of using prebuilt `.dmg` fetched from releases page.

**Comment by momack2** [comment] 2020-05-05 01:30
The last thread I have on the topic is https://github.com/ipfs-shipyard/ipfs-desktop/issues/1067 - where it looks like I installed the beta for 0.9.0. I believe I used the auto-updater after that to get my node to 10.4.

**Comment by rafaelramalho19** [comment] 2020-05-05 11:05
@lidel you have any suggestion oh I can look further into this? I wasn't able to get a response from the community where they also had the same problem as Molly 😕

**Comment by lidel** [comment] 2020-05-05 12:31
@momack2 so the _good news_ is that (so far) we were not able to reproduce the problem with the signed/notarized release versions. 

The only time @rafaelramalho19 was able to get the same error as you was when he run local developer build which was not signed.  Not sure if your setup is similar, or perhaps something you installed along the way had similar impact.

Either way, afaik regular users that installed ipfs-desktop v0.10.4 are not impacted and autoupdate seems to work as expected.

----

@rafaelramalho19 before we close this as "not reproducible" let's make a final check:

Please find someone who had **no prior IPFS installation** and do a fresh install of [v0.10.4](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.10.4) and try to force update to v0.11.2  via menu→about→check for updates

(or manually remove everything that Desktop touches, on linux its:
`rm -rf ~/.ipfs ~/.ipfs-desktop ~/.config/Electron ~/.config/IPFS\ Desktop` )

**Comment by rafaelramalho19** [comment] 2020-05-05 13:07
I asked a colleague of mine to install it and it worked fine. I also did what you said about the clean state and it also worked fine 😄

**Comment by autonome** [comment] 2020-05-05 13:42
Do we have a migration regression test? Would be great to have a test that:

* builds and sign previous version
* configure update url to local web server
* install, and start
* add set of example data
* build and sign current version
* check for updates
* install update

**Comment by momack2** [comment] 2020-05-06 20:56
+1 - we should get that test. 

We should also run a test that installs a random previous version (I think my last one was 0.9.0, which afaik wasn't signed) and then checks for updates manually (or tries to auto-update), to test whether that feature is working.

We also have error logs from countly we can be checking to see other automated reports from users with metrics reporting enabled. Can we use this to estimate the impact of this issue?

**Comment by Stebalien** [comment] 2020-05-07 18:06
I've removed the externally installed go-ipfs version and am still getting this issue with the auto-installed version.

I installed ipfs-desktop not so long ago (a month or two?) through the dmg.

**Comment by Stebalien** [comment] 2020-05-07 18:07
Do we have metrics on how many users managed to upgrade?

**Comment by jessicaschilling** [comment] 2020-05-07 18:18
Here's the version distribution of users since 27 April:
![image](https://user-images.githubusercontent.com/1507828/81329787-465b4900-905c-11ea-8b7a-0c43f32aa803.png)
Top versions are:
- 0.10.4: 3836
- 0.11.2: 2434
- 0.11.1: 345
(0.11.1 was the first version to ship with go-ipfs 0.5)
That represents 2779 upgrades vs 3836 users on 0.10.4, though we can't assure how they upgraded.

**Comment by jessicaschilling** [comment] 2020-05-07 18:19
(this was also discussed in an email chain: @lidel notes "I suspect people are not running IPFS all the time and autoupdate can't happen when Desktop app is not running, so it will take time to migrate everyone.")

**Comment by Stebalien** [comment] 2020-05-07 18:26
Can we distinguish between upgrades and new installs?

---

On topic: I've disabled the gatekeeper and it doesn't make a difference. Something here is borked.

**Comment by jessicaschilling** [comment] 2020-05-07 18:27
> Can we distinguish between upgrades and new installs?
Not that I'm aware of, but I'm new to Countly.

**Comment by jessicaschilling** [comment] 2020-05-07 18:58
Not quite what @Stebalien is asking for, but session frequency is interesting:
![image](https://user-images.githubusercontent.com/1507828/81333624-1ca52080-9062-11ea-880b-eac4fd2cb708.png)
112 first sessions since 27 April, but the vast majority of non-new sessions are on a frequency of at least once a day. This might indicate our auto-update rate should be pretty high even given @lidel's point about auto-update not happening when the app isn't running ...

**Comment by lidel** [comment] 2020-05-18 21:02
@momack2 confirmed that autoupdate worked from [0.11.2](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.11.2)  to [0.11.3](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.11.3) :rocket: 
This means autoupdate on macOS works (at least for people who installed post go-ipfs 0.5.0)

Should we close this?

**Comment by momack2** [comment] 2020-05-19 02:53
Can confirm that our other mac device that wasn't manually upgraded to 11.2 still experiences the previous issue (unable to check for updates) and is stuck on 10.4 without a manual bump.

**Comment by jessicaschilling** [comment] 2020-05-28 19:42
Are we able to close this based on enhancements in https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.11.4 ?

**Comment by lidel** [comment] 2020-05-28 22:11
We can't do more for <0.11.2, but believe 0.11.4 hardens things enough to close this.
@momack2 your call

**Closed** 2020-05-29 15:20 UTC
Labels: P0, area/macos, dif/medium, effort/days, kind/bug, need/analysis, status/in-progress
