### ISSUE TITLE
Error 1/27/2020

### ISSUE THREAD

**Issue by OfficeGeek888** [ipfs-shipyard/ipfs-desktop#1335] opened 2020-01-28 17:06 UTC
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.10.2
- **Electron Version**: 7.1.2
- **Chrome Version**: 78.0.3904.113

**Error**

```
Error: EMFILE: too many open files, open 'C:\Users\Noah Bangs\AppData\Roaming\IPFS Desktop\config.json'
    at Object.openSync (fs.js:447:3)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.readFileSync (fs.js:349:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at ElectronStore.get store [as store] (C:\Users\Noah Bangs\AppData\Local\Programs\IPFS Desktop\resources\app.asar\node_modules\conf\index.js:411:18)
    at ElectronStore.get (C:\Users\Noah Bangs\AppData\Local\Programs\IPFS Desktop\resources\app.asar\node_modules\conf\index.js:288:28)
    at startIpfs$ (C:\Users\Noah Bangs\AppData\Local\Programs\IPFS Desktop\resources\app.asar\out\daemon\index.js:127:48)
    at tryCatch (C:\Users\Noah Bangs\AppData\Local\Programs\IPFS Desktop\resources\app.asar\node_modules\regenerator-runtime\runtime.js:45:40)
```

**Comment by lidel** [comment] 2020-02-03 13:47
Closing as duplicate of https://github.com/ipfs-shipyard/ipfs-desktop/issues/1337

**Closed by lidel** 2020-02-03 13:47 UTC
