### ISSUE TITLE
IPFS Node fails When setting storage location

### ISSUE THREAD

**Issue by lsji07** [ipfs-shipyard/ipfs-desktop#941] opened 2019-05-25 10:00 UTC
Please describe what you were doing when this error happened.

Previously I was running a CLI go-ipfs node. I had to get my ipfs storage to be in my D:\IPFS folder. I run a "small" SSD as my main drive that IPFS woud rapidly fill it (47GB plus currently)

I have to create a IPFS_PATH with value D:\IPFS for a cli node in system variables.
 
Installed the desktop ipfs software and get this error. Seems the desktop version really doesn't like me telling it where to go.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.7.2
- **Electron Version**: 4.0.8
- **Chrome Version**: 69.0.3497.128

**Error**

```
Error: Object has been destroyed
    at ctx.launchWebUI (C:\Users\leigh\AppData\Local\Programs\ipfs-desktop\resources\app.asar\out\late\webui\index.js:92:22)
    at click (C:\Users\leigh\AppData\Local\Programs\ipfs-desktop\resources\app.asar\out\late\tray.js:75:7)
    at MenuItem.click (C:\Users\leigh\AppData\Local\Programs\ipfs-desktop\resources\electron.asar\browser\api\menu-item.js:56:9)
    at Function.executeCommand (C:\Users\leigh\AppData\Local\Programs\ipfs-desktop\resources\electron.asar\browser\api\menu.js:31:13)
```

**Comment by hacdias** [comment] 2019-05-25 10:10
Does it work if you don't set IPFS_PATH?

> Note to self: this error doesn't seem _directly_ related to IPFS_PATH, but with the `window` object being destroyed. Why? Perhaps somewhere else the code is failing, making the object being destroyed.

**Comment by lsji07** [comment] 2019-05-25 12:54
No. I have tried both on fresh installations.

After the intial failure the node doesn't restart or seem to be controlled by the Desktop/menu restart/stop anymore.

Uninstalling and reinstalling doesn't work either as above.

The node shows up as in fault and that is it. I can start a node up separately but the desktop interface doesn't control it etc obviously other than webui reporting.

**Comment by hacdias** [comment] 2019-05-26 07:50
Hmmm... I just tried on a clean installation and there are no issues whatsoever on Windows 10. Could you please share the contents of `%appdata%/IPFS Desktop/error.log`?

**Comment by lsji07** [comment] 2019-05-26 10:15
https://pastebin.com/aRSKYi95

**Comment by hacdias** [comment] 2019-05-27 07:34
@lsji07 I can't reproduce it either, so I'm closing this. Thanks for the report though. If it ever happens again, feel free to reopen 😄

**Closed by hacdias** 2019-05-27 07:34 UTC
