### ISSUE TITLE
Error in installing IPFS desktop on windows

### ISSUE THREAD

**Issue by tycooperaow** [ipfs-shipyard/ipfs-desktop#993] opened 2019-07-22 13:24 UTC
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.8.0
- **Electron Version**: 5.0.2
- **Chrome Version**: 73.0.3683.121

**Error**

```
Error: Command failed: powershell.exe -nop -exec bypass -win hidden C:\Users\Ty Cooper\AppData\Local\Programs\ipfs-desktop\resources\app.asar.unpacked\out\late\ipfs-on-path\scripts\install.ps1
C:\Users\Ty : The term 'C:\Users\Ty' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
  C:\Users\Ty Cooper\AppData\Local\Programs\ipfs-desktop\resources\app. ...
  ~~~~~~~~~~~
      CategoryInfo          : ObjectNotFound: (C:\Users\Ty:String) [], CommandNotFoundException
      FullyQualifiedErrorId : CommandNotFoundException
 

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:194:13)
    at maybeClose (internal/child_process.js:998:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

**Comment by hacdias** [comment] 2019-07-22 17:40
Duplicate of #964. Is fixed for the next release! Sorry for the trouble

**Closed by hacdias** 2019-07-22 17:40 UTC
