### ISSUE TITLE
Desktop client using common development port 8080 

### ISSUE THREAD

**Issue by skinofstars** [ipfs-shipyard/ipfs-desktop#799] opened 2019-01-23 10:14 UTC
Port 8080 is a very common port for anyone running local web development servers, so having the UI listening on that port gives a high chance of conflict.

Why not use an out the way port (e.g. 41256) to avoid any chance of conflict.

**Comment by hacdias** [comment] 2019-01-23 10:46
What is it that is running on 8080? The gateway?

**Comment by skinofstars** [comment] 2019-01-23 10:51
Looks like it, yes

**Comment by hacdias** [comment] 2019-01-23 10:55
Oh, then it is not actually related to IPFS Desktop. It's the daemon running inside, which generally uses the repository at your home directory. You can change the configuration there (`$HOME/.ipfs/config`).

We could change it on development (`npm run start`), but it doesn't make sense to be changing an IPFS Repository configuration for one time runs. The other option would be to have a repository only for development purposes. Although I can't imagine why would that be useful.

I hope it helps!

I'm closing this because this is a duplicate of an issue posted on other repository. Please take a look at: https://github.com/ipfs/go-ipfs/issues/874

😄

**Closed** 2019-01-23 13:58 UTC
