### ISSUE TITLE
TypeError: ctx.manualCheckForUpdates is not a function

### ISSUE THREAD

**Issue by tonuonu** [ipfs-shipyard/ipfs-desktop#1705] opened 2020-10-26 06:49 UTC
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.13.2
- **Electron Version**: 9.3.2
- **Chrome Version**: 83.0.4103.122

**Error**

```
TypeError: ctx.manualCheckForUpdates is not a function
    at click (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/tray.js:198:30)
    at MenuItem.click (electron/js2c/browser_init.js:65:1624)
    at Function.executeCommand (electron/js2c/browser_init.js:73:1102)
```

**Comment by jessicaschilling** [comment] 2020-10-26 14:33
Thanks, @tonuonu - we'll look into this in our next weekly triage.

**Comment by jessicaschilling** [comment] 2020-10-26 16:17
Hi @tonuonu -- quick question. What were you doing when this error happened?

**Comment by jessicaschilling** [comment] 2020-11-02 16:10
Hi @tonuonu -- just checking in about previous question, thanks!

**Comment by tonuonu** [comment] 2020-11-02 17:08
Hi! Sorry about delay. Was overworking and then missed flight and now have jet lag.

I been thinking long how to help you because I do not remember much about what I was exactly doing. And such accurate input is crucial. So my best as I remember:

1. This is brand new Mac, IPFS daemon was possibly installed separately before IPFS Desktop.
2. Everything was stock setup and my aim was to command over port 5001 API which by default listens 127.0.0.1 only
3. If anything, then I possibly changed 5001 ACL to 0.0.0.0 or external IP because I might wanted to access it from other laptop. I might screwed up something, I am not sure anymore.
4. IPFS Desktop kept complaining and offered “restart IPFS desktop” as a way to resolve. When pressed “restart” I got the error I submitted. It was reputable, I submitted just one example.
5. Things went back to normal after I deleted config file from .ipfs directory.

If I somehow find any factual tracks, I tell you. Right now this is all I remember.

    Tõnu

**Comment by jessicaschilling** [comment] 2020-11-02 17:10
@tonuonu - that's a great start, thanks!

@lidel and @rafaelramalho19 - any ideas?

**Comment by jessicaschilling** [comment] 2020-11-09 16:18
Hi @tonuonu - we're unfortunately unable to reproduce this and can't get much further without the config that it sounds like you've deleted. Closing for now, but please be in touch if you experience any similar problems. 

In case anyone reading this runs across this issue again - please reply and attach/excerpt your config file.

**Closed by jessicaschilling** 2020-11-09 16:18 UTC

**Comment by tonuonu** [comment] 2020-11-09 18:10
Thank You! I try to report if I know something.
