### ISSUE TITLE
 IPFS command line tools 

### ISSUE THREAD

**Issue by artistjw** [ipfs-shipyard/ipfs-desktop#1317] opened 2020-01-11 07:29 UTC
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: linux
- **IPFS Desktop Version**: 0.10.2
- **Electron Version**: 7.1.2
- **Chrome Version**: 78.0.3904.113

**Error**

```
Error: Unable to find pkexec or kdesudo.
    at test (/snap/ipfs-desktop/7/resources/app.asar/node_modules/sudo-prompt/index.js:205:18)
    at /snap/ipfs-desktop/7/resources/app.asar/node_modules/sudo-prompt/index.js:212:47
    at FSReqCallback.oncomplete (fs.js:165:21)
```

**Comment by hacdias** [comment] 2020-04-24 07:41
Duplicate of #1311.

**Closed by hacdias** 2020-04-24 07:41 UTC
