### ISSUE TITLE
Feature: Add command line access

### ISSUE THREAD

**Issue by hazae41** [ipfs-shipyard/ipfs-desktop#898] opened 2019-04-09 21:06 UTC
It would be useful if we could access the go-ipfs command line from the app

**Comment by hacdias** [comment] 2019-04-09 21:37
Hello @Hazae41! Do you mean adding `ipfs` to the PATH so you can access it through the command line? If so, it's in the works and this is a duplicate of #727 😄

**Comment by Hazae41** [comment] 2019-04-10 16:05
No, sorry, I mean a command line in the GUI itself

**Comment by hacdias** [comment] 2019-04-10 21:38
@hazae41 how'd you suggest us to do so?

**Comment by hazae41** [comment] 2019-04-10 22:23
Maybe a new page in the webui
or a new window

**Comment by hacdias** [comment] 2019-04-10 22:53
But why would you need this if you'll be able to access it through the command line?

**Comment by hazae41** [comment] 2019-04-11 17:26
We can access the IPFS configuration through the webui, why not the command line?

**Comment by hacdias** [comment] 2019-04-12 21:24
I don't know to which point it would make sense to have a command line interface available through a web page when you can just use it on your terminal. Could you please explain some use cases?

/cc @ipfs-shipyard/gui

**Comment by hazae41** [comment] 2019-04-14 05:44
Well sometimes end-users need to allow HTTP origins and they are given commands to type

**Comment by olizilla** [comment] 2019-04-16 08:49
The cases where the web ui shows an example shell command, are those times where the web ui can't do the action required. The user _must_ use the command line to do them, as the http api  is unavailable either due to CORS config or the daemon not running.

It might be neat to have a power user feature that lets you try out IPFS commands in the browser. We could use that as an opportunity to teach the user more about the meaning of the commands and how to interpret the responses.

It'd be a significant chunk of work. @hazae41 have you got more info on what situation you ran into that made you see the need for this? What's was your use case?

**Closed** 2019-04-25 17:35 UTC
