### ISSUE TITLE
"system interrupts" process goes through the roof

### ISSUE THREAD

**Issue by ruifortes** [ipfs-shipyard/ipfs-desktop#1719] opened 2020-12-16 11:06 UTC
Hi.
Can't figure out what triggers it but it happens when "IPFS Companion" is running and stops when I close it.
The "system interrupts" process goes 100% (or whatever proportional percentage...) and pretty much slown the system to a crawl.
Any tests I could do?

 - OS: Windows 10
 - Browser: Brave
 - Version: v0.13.2

**Comment by jessicaschilling** [comment] 2021-01-04 19:03
@ruifortes - when you say "disabled Chrome extension" do you mean one of the following? And if so, which one?
- Turned "off" IPFS Companion via the "power button" in browser menu (![2020-12-16--18-32-09](https://user-images.githubusercontent.com/157609/102384474-0cc4c600-3fcd-11eb-8936-d1596f22df75.png))
- Disabled IPFS Companion extension entirely via `brave://extensions/`

**Comment by ruifortes** [comment] 2021-01-07 09:40
I just turned it off via "power button".
I'm gonna disable the extension now and then get back to you

**Comment by ruifortes** [comment] 2021-01-07 12:25
Same thing with companion extension disabled.
After a while "system interrupts" goes berserk and all send OS to a crawl.
Didn't do anything to IPFS, just started it. Didn't add any files nor even opened the GUI
Trying now without karspersky

**Comment by ruifortes** [comment] 2021-01-07 13:30
ipfs.exe just started to consume lots of resources (disk and cpu) without me having any interaction with it.

**Comment by ruifortes** [comment] 2021-01-07 13:41
and now it stopped... there was some activity "bucker refresh" activity in "ipfs stats dht" but I don't think I have any publically accessable resources

**Comment by lidel** [comment] 2021-01-08 11:29
@ruifortes thank you for debugging this, this is very useful!

You confirm my suspicion that the problem is not originated in IPFS Desktop codebase, but go-ipfs daemon (`ipfs.exe`) running DHT client for a while on Windows 10 platform. 

Do you mind closing this issue and opening a new Bug Report in https://github.com/ipfs/go-ipfs/issues/new/choose?   :pray:

**Comment by ruifortes** [comment] 2021-01-08 14:27
Hi.
Running IPFS desktop without Kaspersky took more time but eventually also got the "system interrupts" problem

**Comment by ruifortes** [comment] 2021-01-08 14:30
@lidel sure, I'll post there and link to this issue

**Comment by lidel** [comment] 2021-01-08 16:14
Thanks! Let's continue in https://github.com/ipfs/go-ipfs/issues/7854 with go-ipfs team.

**Closed by lidel** 2021-01-08 16:14 UTC
Labels: need/author-input
