### ISSUE TITLE
Crash on connection error

### ISSUE THREAD

**Issue by agentofuser** [ipfs-shipyard/ipfs-desktop#902] opened 2019-04-09 23:08 UTC
I didn't do anything in particular. Went out to dinner, came back and the app had crashed and showed me the dialog to report the error. I think my internet connection had a hiccup in that time, because an unrelated git clone also failed.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.6.1
- **Electron Version**: 4.0.0
- **Chrome Version**: 69.0.3497.106

**Error**

```
Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
```

**Comment by hacdias** [comment] 2019-04-10 07:09
Duplicate of #895, #776 and #787. Please update to the latest version 😃

**Closed by hacdias** 2019-04-10 07:09 UTC

**Comment by agentofuser** [comment] 2019-04-11 12:29
Thank you! I'm going with `brew cask install ipfs` now to help keep things up to date :)
