### ISSUE TITLE
Doesn't work with Bandwidth Reporter disabled

### ISSUE THREAD

**Issue by sergeevabc** [ipfs-shipyard/ipfs-desktop#893] opened 2019-04-01 12:44 UTC
Windows 7 x64 -> ipfs-desktop-setup-0.7.2.exe

Tray icon says ```IPFS is running```, but clicking upon Status/Files/Settings outputs ```Is your IPFS daemon running? Failed to connect to the API```. However I see ```ipfs.exe``` within processes listed in Windows Task Manager.

I have read advices below such as “allow cross-origin”, but provided command ```ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["webui://-", "http://127.0.0.1:5001", "https://webui.ipfs.io"]'``` throws error ```“Error: Unknown Command "API.HTTPHeaders.Access-Control-Allow-Origin"```.

Thus, I’m confused.

**Comment by hacdias** [comment] 2019-04-02 07:43
That's curious. I can't reproduce your issue on Windows 10. Have you changed any configuration/did you have a repository before installing IPFS Desktop? Or this is your first time installing IPFS?

**Comment by sergeevabc** [comment] 2019-04-02 09:40
@hacdias, first time user, yes. Even turned off built-in Windows firewall just in case. It is regrettable there is no bootstrapping log to provide for easier troubleshooting since ```…\IPFS Desktop\logs``` is empty and other two log-like files contain vague information as follows.
```
$ cat combined.log
2019-04-02T09:30:39.950Z error: net::ERR_EMPTY_RESPONSE
2019-04-02T09:30:42.392Z info: [web ui] window ready
2019-04-02T09:30:42.393Z info: [tray] starting
2019-04-02T09:30:42.701Z info: [tray] started
2019-04-02T09:30:42.703Z info: [ipfsd] starting daemon
2019-04-02T09:30:51.425Z info: [ipfsd] daemon started
2019-04-02T09:30:51.529Z info: [hash download] shortcut disabled
2019-04-02T09:30:51.530Z info: [screenshot] shortcut disabled
2019-04-02T09:30:51.577Z info: [launch on startup] disabled
2019-04-02T09:31:41.689Z info: [web ui] navigate to /

$ cat error.log
2019-04-02T09:30:39.950Z error: net::ERR_EMPTY_RESPONSE
```

**Comment by hacdias** [comment] 2019-04-03 17:36
Are you using Windows Subsystem for Linux? How did you run `ipfs` command if IPFS Desktop doesn't provide the CLI (yet)? You seem to already have IPFS running on your computer somehow.

**Comment by sergeevabc** [comment] 2019-04-03 18:30
@hacdias, -_-
My OS was stated clearly in the beginning, it is Windows 7, it has no Linux Subsystem.
And I never run any ipfs commands via command-line interface.
What I did is switched off IPFS Desktop, went to its logs folder and shared its contents with you.

**Comment by hacdias** [comment] 2019-04-05 08:35
> I have read advices below such as “allow cross-origin”, but provided command ```ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["webui://-", "http://127.0.0.1:5001", "https://webui.ipfs.io"]'``` throws error ```“Error: Unknown Command "API.HTTPHeaders.Access-Control-Allow-Origin"```.

How did you run that? We don't provide the `ipfs` CLI.

Could you try killing all ipfs-related processes in taskmgr and restart IPFS Desktop, please?

**Comment by NatoBoram** [comment] 2019-04-06 00:46
Confirmed here, it doesn't work out of the box anymore.

```yaml
OS: Windows 10 Pro x86_64
Host: System manufacturer
Kernel: 2.11.2(0.329/5/3)
Uptime: 11 hours, 21 mins
Shell: bash 4.4.23
Resolution: 1920x1080
DE: Aero
WM: Explorer
WM Theme: Roamed
CPU: Intel i5-3570K (4) @ 3.410GHz
GPU: NVIDIA GeForce GTX 660 Ti
Memory: 6411MiB / 8135MiB
```

![image](https://user-images.githubusercontent.com/10495562/55662589-bc9ad580-57e2-11e9-9636-b50f038956f8.png)

Also, those two commands...

```batch
$ ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["webui://-", "http://127.0.0.1:5001", "https://webui.ipfs.io"]'
$ ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["PUT", "GET", "POST"]'
```

Here's their output :

```batch
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["webui://-", "http://127.0.0.1:5001", "https://webui.ipfs.io"]'
Error: Unknown Command "API.HTTPHeaders.Access-Control-Allow-Origin"


USAGE
  ipfs config <key> [<value>] - Get and set ipfs config values.

  ipfs config [--bool] [--json] [--] <key> [<value>]

  'ipfs config' controls configuration variables. It works like 'git config'.
  The configuration values are stored in a config file inside your ipfs
  repository.

SUBCOMMANDS
  ipfs config edit           - Open the config file for editing in $EDITOR.
  ipfs config profile        - Apply profiles to config.
  ipfs config replace <file> - Replace the config with <file>.
  ipfs config show           - Output config file contents.

Use 'ipfs config --help' for more information about this command.
```

```batch
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["PUT", "GET", "POST"]'
Error: Unknown Command "API.HTTPHeaders.Access-Control-Allow-Methods"


USAGE
  ipfs config <key> [<value>] - Get and set ipfs config values.

  ipfs config [--bool] [--json] [--] <key> [<value>]

  'ipfs config' controls configuration variables. It works like 'git config'.
  The configuration values are stored in a config file inside your ipfs
  repository.

SUBCOMMANDS
  ipfs config edit           - Open the config file for editing in $EDITOR.
  ipfs config profile        - Apply profiles to config.
  ipfs config replace <file> - Replace the config with <file>.
  ipfs config show           - Output config file contents.

Use 'ipfs config --help' for more information about this command.
```

However, IPFS Companion's WebUI **does** work.

Here's the logs I've got : 

```log
Failed to connect to ipfs-api /ip4/127.0.0.1/tcp/5001
4.56d25521.chunk.js:1 Trying IPFS Companion
4.56d25521.chunk.js:1 🎛️ Customise your js-ipfs-api options by storing a `ipfsApi` object in localStorage. e.g. localStorage.setItem('ipfsApi', '/ip4/127.0.0.1/tcp/5001')
4.56d25521.chunk.js:1 Trying ipfs-api with custom api address /ip4/127.0.0.1/tcp/5001
bw:1 Failed to load resource: the server responded with a status of 503 (Connect failed)
```

**Comment by hacdias** [comment] 2019-04-06 10:54
Just installed a fresh VM with Windows 10 Pro, downloaded right from GitHub releases and no issues whatsoever. I'm really confused with what might be happening. Maybe a firewall issue?

Used this binary:

https://github.com/ipfs-shipyard/ipfs-desktop/releases/download/v0.7.2/ipfs-desktop-setup-0.7.2.exe

Screenshot from VM:

![image](https://user-images.githubusercontent.com/5447088/55668461-9c126000-5862-11e9-96e6-46bd48a35d00.png)

Also tried on my other Windows computer and it works just fine.

---

About the commands, yes, they don't work on Windows due to PowerShell different escaping. We should change that on Web UI @olizilla

**Comment by NatoBoram** [comment] 2019-04-08 04:39
Ugh, what a pain. I have no idea what can cause this, I'm running a fresh build that I installed literally three days ago. Even in my old Windows installation, it stopped working a few weeks ago.

**Comment by hacdias** [comment] 2019-04-08 08:11
Yeah, this is a weird situation. Do you know more or less in which version it stopped working? Did it stop working with an already existing IPFS repo?

**Comment by NatoBoram** [comment] 2019-04-10 03:57
Nope. It just stopped working after an update. I tried both an existing repo and without a repo, with badgerds and flatfs, installed from Scoop and installed from the installer, and now from a fresh Windows 10 installation.

**Comment by hacdias** [comment] 2019-04-10 07:19
I tried the exact same situations and didn't have any issue. Let's bring someone else! @djdv, could you please try to see if you can reproduce this issue? Thanks 😃

**Comment by djdv** [comment] 2019-04-10 17:55
Okay so, without ipfs-desktop. I was unable to connect to the webui using my `go-ipfs` daemon, but these where unrelated (https://github.com/ipfs-shipyard/ipfs-webui/issues/1008, https://github.com/ipfs-shipyard/ipfs-webui/issues/1009) and already mentioned above. It had to do with my custom configuration.

I installed an instance of latest version of Windows (10 1903 18362.53), installed ipfs-desktop, and had no issues with a fresh profile.
![desktop](https://user-images.githubusercontent.com/13862850/55901893-4c040800-5b98-11e9-8c12-1b9fea237aa9.png)


For people having the issue, can you open the ipfs-desktop status window, open the console (ctrl+shift+i), reload the page (ctrl+r), and see if you encounter any error similar to this: https://github.com/ipfs-shipyard/ipfs-webui/issues/1009

**Comment by NatoBoram** [comment] 2019-04-10 19:16
Oh, that worked for me. I though I had enabled everything after creating the node, but it looks like it wasn't the case.

So... Shouldn't IPFS Desktop try to launch this command in the background if it can't connect to the node?

**Comment by djdv** [comment] 2019-04-10 19:57
In my case, I went from a non-existing ipfs-config, and let ipfs-desktop initialize the profile. It seems like if you have an existing profile, nothing is modified.
https://github.com/ipfs-shipyard/ipfs-desktop/blob/19a8793cc7e7b8ccbbce794fad46ca23fa450d00/src/utils/daemon.js#L55-L57

So currently, you either need a modern default config already, or you have to set those values yourself.

>Shouldn't IPFS Desktop try to launch this command in the background if it can't connect to the node?

It seems like it would be useful to have an option that applies required settings to the config file. Basically a "Reset config" option during install, or a menu item under Advanced, etc.
But imo we should not override the config values automatically, without prompting the user.

**Comment by NatoBoram** [comment] 2019-04-10 20:14
So just adding that command to the interface, where the two others are, should be enough.

**Comment by sergeevabc** [comment] 2019-04-10 20:22
@NatoBoram, “that command, that command”, let’s say it loud and clear:
`ipfs config --json Swarm.DisableBandwidthMetrics false`

**Comment by hacdias** [comment] 2019-04-10 22:52
Thanks for debugging this @djdv. I think that the best option is to show in Web UI some kind of message in this situations instead of blacking out. What do you think @olizilla?

We could, perhaps, make Web UI "tell" Desktop somehow of this issue, and ask the user their permission to automatically change the configuration instead of them doing it manually.

**Comment by hacdias** [comment] 2019-04-30 21:38
Fixed on https://github.com/ipfs-shipyard/ipfs-webui/pull/1024 :smiley:

**Closed by hacdias** 2019-04-30 21:38 UTC
