### ISSUE TITLE
IDK What happened

### ISSUE THREAD

**Issue by musashi39** [ipfs-shipyard/ipfs-desktop#1356] opened 2020-02-21 09:13 UTC
Please describe what you were doing when this error happened.
I got an extension could be corrupt and after clicking repair and restarting this happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.10.3
- **Electron Version**: 7.1.11
- **Chrome Version**: 78.0.3904.130

**Error**

```
Error: spawn powershell.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Comment by hacdias** [comment] 2020-04-24 07:43
Duplicate of #1348.

However, I'm interested: which extension? Also, you should have powershell installed. That's odd. Please feel free to reply to my question on #1348.

**Closed by hacdias** 2020-04-24 07:43 UTC
