### ISSUE TITLE
Investigation: 'Cannot read property 'pid' of null'

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs-shipyard/ipfs-desktop#1713] opened 2020-11-30 16:43 UTC
We're seeing a variety of reports of `TypeError: Cannot read property 'pid' of null` in Desktop but no clear root cause. Need to investigate whether the crash reports we are seeing are actually a side effect of something else. Collating all current/closed reports of this error here for the sake of beginning an investigation:

https://github.com/ipfs-shipyard/ipfs-webui/issues/1670
https://github.com/ipfs-shipyard/ipfs-desktop/issues/1702
https://github.com/ipfs-shipyard/ipfs-desktop/issues/1711
https://github.com/ipfs-shipyard/ipfs-desktop/issues/1706
https://github.com/ipfs-shipyard/ipfs-desktop/issues/1714
https://github.com/ipfs-shipyard/ipfs-desktop/issues/1482 (may not be relevant)
https://github.com/ipfs-shipyard/ipfs-desktop/issues/1479 (may not be relevant)
https://github.com/ipfs-shipyard/ipfs-desktop/issues/1723 (related - see below comment - but this error is `TypeError: ctx.manualCheckForUpdates is not a function`)

**Comment by jjv360** [comment] 2020-12-29 11:28
Hi, I'm getting this error on IPFS Desktop on Windows 10 (version 0.13.2)... Steps to reproduce:
- Run `ipfs daemon` from a terminal window
- Start IPFS Desktop
- Close the terminal that was running `ipfs daemon`
- Press Restart from the tray menu
- Wait about 10 seconds

I assume IPFS desktop can't handle switching from a manual `ipfs daemon` to it's own built-in one... But I have to run it this way unfortunately (#1723)

**Comment by lidel** [comment] 2021-02-23 21:08
I believe this was caused by the bug fixed in https://github.com/ipfs/js-ipfsd-ctl/pull/554 
We bumped `ipfsd-ctl` to new version in https://github.com/ipfs-shipyard/ipfs-desktop/pull/1735#pullrequestreview-571756458
and now restarting multiple times and switching back and forth seems to work as expected.

I am closing this, assuming it will be fixed in next release (0.14.0)

**Closed by lidel** 2021-02-23 21:08 UTC
