### ISSUE TITLE
Failed to enable IPFS CLI from IPFS Desktop on Debian/Ubuntu based OS

### ISSUE THREAD

**Issue by jamescallumyoung** [ipfs-shipyard/ipfs-desktop#1401] opened 2020-04-15 19:03 UTC
I was trying to enable the ipfs CLI binary after installing the IPFS Desktop app.

The app was installed via snap, on a Debian/Ubuntu based machine.

My machine specs follow:
elementary OS 5.1.3 Hera
Built on Ubuntu 18.04.3 LTS
Linux 4.15.0-96-generic
GTK 3.22.30

The log  states the error ocurred when trying to find `pkexec` and/or `kdesudo`. I checked my local system and `pkexec` is present at `/usr/bin` (which is in my PATH).

I suspect this may be a permission issue since I am running the snap package of IPFS Desktop and snap's are sandboxed. I'm not too familiar with snap development however, so I could be wrong.

**Specifications**

- **OS**: linux (elementaryOS
- **IPFS Desktop Version**: 0.10.4
- **Electron Version**: 7.1.14
- **Chrome Version**: 78.0.3904.130

**Error**

```
Error: Unable to find pkexec or kdesudo.
    at test (/snap/ipfs-desktop/9/resources/app.asar/node_modules/sudo-prompt/index.js:205:18)
    at /snap/ipfs-desktop/9/resources/app.asar/node_modules/sudo-prompt/index.js:212:47
    at FSReqCallback.oncomplete (fs.js:165:21)
```

**Comment by jamescallumyoung** [comment] 2020-04-15 19:05
I was prompted to create this issue from the Desktop app. I've just checked other open issues and found that this seems to be a duplicate of #1386 .

**Comment by hacdias** [comment] 2020-04-24 07:48
Closing as duplicate of #1311.

And you're right, it probably is related to Snap and it's sandboxing. It's also weird that you're not getting a prompt. I'll check on this.

**Closed by hacdias** 2020-04-24 07:48 UTC
Labels: need/triage
