### ISSUE TITLE
Adding a folder to upload in files tab does not work

### ISSUE THREAD

**Issue by jonnybravocoder** [ipfs-shipyard/ipfs-desktop#1346] opened 2020-02-09 04:38 UTC
**Describe the bug**
In the ipfs desktop application, when attempting to add multiple files to ipfs by adding a directory, no files are added.  In fact, it looks like nothing is happening at all..  Also, the "report a bug" hyperlink in the bottom left hand corner of the ipfs desktop application links to the github issues page for the ipfs-webui repo. I could be wrong, but I am thinking that is a mistake.

![2020-02-08 23_31_50-_ - Files - IPFS](https://user-images.githubusercontent.com/60832831/74096374-112a7380-4acc-11ea-8cc9-a312c5970706.png)
 

**To Reproduce**
I did you one better and recorded my screen and uploaded the video reproducing the error.  Take a look:
https://showmore.com/u/zq5yluv

**Expected behavior**
The files in the folder to be added to ipfs

**Screenshots**
Please watch video linked above.

**Desktop (please complete the following information):**
 - OS: Windows 10 pro x64
 - Browser NA
 - Version 0.10.3

**Smartphone (please complete the following information):**
Using a Windows 10 computer

**Comment by jheeffer** [comment] 2020-03-28 02:44
I have the same problem. Adding a folder through desktop (+Add button -> Folder -> Select Folder) does nothing. Adding a folder through the windows context menu does work though.

**Comment by lidel** [comment] 2020-04-03 22:53
Thank you for reporting this from Windows: seems that the issue is not specific to unix-like systems.
I believe this is the same bug as https://github.com/ipfs-shipyard/ipfs-desktop/issues/1287, let's track it there, closing as duplicate.

**Closed by lidel** 2020-04-03 22:53 UTC
Labels: area/webui, kind/bug
