### ISSUE TITLE
Option to only start Frontend

### ISSUE THREAD

**Issue by 6543** [ipfs-shipyard/ipfs-desktop#611] opened 2018-03-14 22:22 UTC
How can i start ipfs-desktop without starting the ipfs daemon?

because i have ipfs running alrady as daemon (https://github.com/6543/ipfs_daemon)

**Comment by dryajov** [comment] 2018-03-14 22:31
This would require https://github.com/ipfs/js-ipfsd-ctl/issues/182 to be completed.

**Comment by lidel** [comment] 2018-03-14 23:35
Also, this seems to be a duplicate of https://github.com/ipfs-shipyard/ipfs-desktop/issues/542 :)

**Comment by 6543** [comment] 2018-10-24 23:48
> Also, this seems to be highly related to #542 :)

I agree have, but faire enouth, i forgott to mentiont that my daemon is running on my nas.
and i point tools like the [ipfs companion](https://github.com/ipfs-shipyard/ipfs-companion) to this IP.

Should I open a new issue or rename this one to something like "Use Frontend with external ipfs daemon" ?

**Closed** 2018-10-24 23:53 UTC
Labels: ready
