### ISSUE TITLE
Error with IPFS

### ISSUE THREAD

**Issue by resslerruntime** [ipfs-shipyard/ipfs-desktop#966] opened 2019-06-29 06:43 UTC
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.8.0
- **Electron Version**: 5.0.2
- **Chrome Version**: 73.0.3683.121

**Error**

```
Error: Command failed: /Applications/IPFS Desktop.app/Contents/MacOS/IPFS Desktop /Applications/IPFS Desktop.app/Contents/Resources/app.asar/out/late/ipfs-on-path/scripts/install.js --data="/Users/macresslertech/Library/Application Support/IPFS Desktop"
/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:45
        throw err0
        ^

Error: EACCES: permission denied, mkdir '/usr/local/bin'
    at Object.mkdirSync (fs.js:778:3)
    at mkdirsSync (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:31:9)
    at Object.createSymlinkSync (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/fs-extra/lib/ensure/symlink.js:56:3)
    at Object.<anonymous> (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/out/late/ipfs-on-path/scripts/install.js:61:4)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:873:10)

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:194:13)
    at maybeClose (internal/child_process.js:998:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

**Comment by hacdias** [comment] 2019-07-03 06:47
Duplicate of #959

**Closed by hacdias** 2019-07-03 06:47 UTC
