### ISSUE TITLE
Error in a Macbook

### ISSUE THREAD

**Issue by diegotco** [ipfs-shipyard/ipfs-desktop#960] opened 2019-06-13 03:01 UTC
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.8.0
- **Electron Version**: 5.0.2
- **Chrome Version**: 73.0.3683.121

**Error**

```
Error: Command failed: /Applications/IPFS Desktop.app/Contents/MacOS/IPFS Desktop /Applications/IPFS Desktop.app/Contents/Resources/app.asar/out/late/ipfs-on-path/scripts/install.js --data="/Users/bitso/Library/Application Support/IPFS Desktop"
fs.js:122
    throw err

**Comment by hacdias** [comment] 2019-06-13 10:12
Duplicate of #959

**Closed by hacdias** 2019-06-13 10:12 UTC
