### ISSUE TITLE
Error: Unable to find pkexec or kdesudo with the snap version (OpenSUSE)

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [ipfs-shipyard/ipfs-desktop#1173] opened 2019-10-06 10:34 UTC
Please describe what you were doing when this error happened.
Exactly like my previous #1113 issue, but this time, with OpenSUSE.
I´m unable to add the command line tools from the ipfs-desktop snap application. (If you ask why i didn´t preffered using the .rpm package, that´s because it require a dependency that doesn´t seems to be available in my system repos (libXtst))

**Specifications**
```bash
                                     ......
     .,cdxxxoc,.               .:kKMMMNWMMMNk:.
    cKMMN0OOOKWMMXo. ;        ;0MWk:.      .:OMMk.     pm@Velvet4Renaissance 
  ;WMK;.       .lKMMNM,     :NMK,             .OMW;    --------------------- 
 cMW;            'WMMMN   ,XMK,                 oMM'   OS: openSUSE Tumbleweed x86_64 
.MMc               ..;l. xMN:                    KM0   Host: MS-7918 1.0 
'MM.                   'NMO                      oMM   Kernel: 5.3.1-1-default 
.MM,                 .kMMl                       xMN   Uptime: 1 hour, 36 mins 
 KM0               .kMM0. .dl:,..               .WMd   Packages: 2715 (rpm), 6 (flatpak), 7 (snap) 
 .XM0.           ,OMMK,    OMMMK.              .XMK    Shell: bash 5.0.11 
   oWMO:.    .;xNMMk,       NNNMKl.          .xWMx     Resolution: 3440x1440 
     :ONMMNXMMMKx;          .  ,xNMWKkxllox0NMWk,      DE: Plasma 
         .....                    .:dOOXXKOxl,         WM: KWin 
                                                       WM Theme: Layan 
                                                       Theme: Breeze-Dark [GTK2/3] 
                                                       Icons: Tela-dark [GTK2/3] 
                                                       Terminal: yakuake 
                                                       CPU: Intel i7-4790 (8) @ 4.000GHz 
                                                       GPU: NVIDIA GeForce GTX 1060 6GB 
                                                       Memory: 4831MiB / 32053MiB 
```
- **OS**: linux
- **IPFS Desktop Version**: 0.9.4
- **Electron Version**: 6.0.10
- **Chrome Version**: 76.0.3809.146

**Error**

```
Error: Unable to find pkexec or kdesudo.
    at test (/snap/ipfs-desktop/1/resources/app.asar/node_modules/sudo-prompt/index.js:205:18)
    at /snap/ipfs-desktop/1/resources/app.asar/node_modules/sudo-prompt/index.js:212:47
    at FSReqCallback.oncomplete (fs.js:165:21)
```

**Comment by hacdias** [comment] 2019-10-06 11:00
Hello @PoorPocketsMcNewHold! The previous issue (#1113) was actually caused by a bug. This one might not be: to enable `ipfs` on `PATH`, we need `sudo` permissions to make changes. For that, we are using [`sudo-prompt`](https://github.com/jorangreef/sudo-prompt#readme) to get a confirmation from the user.

Some Linux distributions might not have the required software for that. It seems `sudo-prompt` is telling us your system does not have either `pkexec`, nor `kdesudo`. Perhaps it's just the "snapped" package that does not have permission to access those files.

Can you check if they exist, please?

**Comment by hacdias** [comment] 2019-11-27 18:54
I'm closing this since I have not gotten a response. Please feel free to reopen this in the future or open a new issue!

**Closed by hacdias** 2019-11-27 18:54 UTC

**Comment by PoorPocketsMcNewHold** [comment] 2019-12-21 11:07
Had this same issue on Solus this time, so I’m taking the liberty to reopen this as I’m encountering this issue once again.
And as expected, either pkexec or kdesudo is present (Nor installable) on the system.
```
            -```````````                  pm@vix 
          `-+/------------.`              ------ 
       .---:mNo---------------.           OS: Solus x86_64 
     .-----yMMMy:---------------.         Kernel: 5.3.15-138.current 
   `------oMMMMMm/----------------`       Uptime: 5 hours, 19 mins 
  .------/MMMMMMMN+----------------.      Packages: 1220 (eopkg), 4 (flatpak), 9 (snap) 
 .------/NMMMMMMMMm-+/--------------.     Shell: bash 5.0.11 
`------/NMMMMMMMMMN-:mh/-------------`    Resolution: 3440x1440 
.-----/NMMMMMMMMMMM:-+MMd//oso/:-----.    DE: Budgie 
-----/NMMMMMMMMMMMM+--mMMMh::smMmyo:--    Theme: Layan-light [GTK2/3] 
----+NMMMMMMMMMMMMMo--yMMMMNo-:yMMMMd/.   Icons: Tela-purple-dark [GTK2/3] 
.--oMMMMMMMMMMMMMMMy--yMMMMMMh:-yMMMy-`   Terminal: guake 
`-sMMMMMMMMMMMMMMMMh--dMMMMMMMd:/Ny+y.    CPU: AMD Ryzen 5 3600X 6- (12) @ 3.800GHz 
`-/+osyhhdmmNNMMMMMm-/MMMMMMMmh+/ohm+     GPU: NVIDIA GeForce GTX 1060 6GB 
  .------------:://+-/++++++oshddys:      Memory: 4751MiB / 32044MiB 
   -hhhhyyyyyyyyyyyhhhhddddhysssso-
    `:ossssssyysssssssssssssssso:`                                
      `:+ssssssssssssssssssss+-                                   
         `-/+ssssssssssso+/-`
              `.-----..`

```
