### ISSUE TITLE
error during first Launching 

### ISSUE THREAD

**Issue by emanresu-web** [ipfs-shipyard/ipfs-desktop#1028] opened 2019-08-11 19:31 UTC
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.8.0
- **Electron Version**: 5.0.2
- **Chrome Version**: 73.0.3683.121

**Error**

```
Error: Command failed: /Applications/IPFS Desktop.app/Contents/MacOS/IPFS Desktop /Applications/IPFS Desktop.app/Contents/Resources/app.asar/out/late/ipfs-on-path/scripts/install.js --data="/Users/Apple/Library/Application Support/IPFS Desktop"
fs.js:122
    throw err

**Comment by emanresu-web** [comment] 2019-08-11 19:32
[error Launching IPFS.log](https://github.com/ipfs-shipyard/ipfs-desktop/files/3490359/error.Launching.IPFS.log)

**Comment by hacdias** [comment] 2019-08-11 20:10
Duplicate of #959. Fixed for the next release!

**Closed by hacdias** 2019-08-11 20:10 UTC

**Comment by emanresu-web** [comment] 2019-08-11 20:15
Thx for the update%$
