### ISSUE TITLE
Issue with the app after updating to v0.11.1

### ISSUE THREAD

**Issue by danrobi11** [ipfs-shipyard/ipfs-desktop#1475] opened 2020-04-30 00:17 UTC
Thats what I did:
1- sudo apt remove ipfs-desktop
2- Installed the new v0.11.1 deb file (same result with appimage)
Now when I start ipfs-desktop I think it opens 2 ipfs-desktop instance.
It wont show up in systray and it wont connect with my Galacteek app.
Everything seems broken. Although I see peers so im connected with the network.
Im a non-technical user best I can do sry. I've the terminal history for you. Plz help. Thx!
MX Linux MX x86_64 (no systemd)
Kernel: 4.19.0-6-amd64
DE: Xfce
```
$ ipfs-desktop
2020-04-29T19:11:03.875Z info: [meta] logs can be found on /home/danrobi/.config/IPFS Desktop
Checking for update
Error: Error: ENOENT: no such file or directory, open '/opt/IPFS Desktop/resources/app-update.yml'
2020-04-29T19:11:04.591Z error: [updater] Error: ENOENT: no such file or directory, open '/opt/IPFS Desktop/resources/app-update.yml'
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
2020-04-29T19:11:05.040Z info: [web ui] window ready
2020-04-29T19:11:05.041Z info: [web ui] navigate to /
2020-04-29T19:11:05.058Z info: [tray] starting
2020-04-29T19:11:05.101Z info: [tray] started
2020-04-29T19:11:05.103Z info: [ipfsd] start daemon STARTED
2020-04-29T19:11:06.292Z info: [daemon] PeerID is Qmbu6...
2020-04-29T19:11:06.293Z info: [daemon] Repo is at /home/username/.ipfs
Error: ENOENT, node_modules/countly-sdk-nodejs/data/__cly_event.json not found in /opt/IPFS Desktop/resources/app.asar
    at createError (electron/js2c/asar.js:111:17)
    at Object.func [as openSync] (electron/js2c/asar.js:146:27)
    at Object.writeFileSync (fs.js:1265:35)
    at storeSet (/opt/IPFS Desktop/resources/app.asar/node_modules/countly-sdk-nodejs/lib/countly.js:1337:16)
    at add_cly_events (/opt/IPFS Desktop/resources/app.asar/node_modules/countly-sdk-nodejs/lib/countly.js:498:13)
    at Object.Countly.add_event (/opt/IPFS Desktop/resources/app.asar/node_modules/countly-sdk-nodejs/lib/countly.js:475:13)
    at Object.end (/opt/IPFS Desktop/resources/app.asar/src/common/logger.js:50:19)
    at startIpfs (/opt/IPFS Desktop/resources/app.asar/src/daemon/index.js:65:11)
    at async module.exports (/opt/IPFS Desktop/resources/app.asar/src/daemon/index.js:120:3)
    at async run (/opt/IPFS Desktop/resources/app.asar/src/index.js:72:5)
2020-04-29T19:11:06.296Z info: [ipfsd] start daemon FINISHED 1.189671929001808s
2020-04-29T19:11:06.315Z info: [ipfs on path] no action taken
2020-04-29T19:11:06.315Z info: [launch on startup] disabled
Error: ENOENT, node_modules/countly-sdk-nodejs/data/__cly_queue.json not found in /opt/IPFS Desktop/resources/app.asar
    at createError (electron/js2c/asar.js:111:17)
    at Object.func [as openSync] (electron/js2c/asar.js:146:27)
    at Object.writeFileSync (fs.js:1265:35)
    at storeSet (/opt/IPFS Desktop/resources/app.asar/node_modules/countly-sdk-nodejs/lib/countly.js:1337:16)
    at toRequestQueue (/opt/IPFS Desktop/resources/app.asar/node_modules/countly-sdk-nodejs/lib/countly.js:985:13)
    at Timeout._onTimeout (/opt/IPFS Desktop/resources/app.asar/node_modules/countly-sdk-nodejs/lib/countly.js:354:17)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
Error: ENOENT, node_modules/countly-sdk-nodejs/data/__cly_queue.json not found in /opt/IPFS Desktop/resources/app.asar
    at createError (electron/js2c/asar.js:111:17)
    at Object.func [as openSync] (electron/js2c/asar.js:146:27)
    at Object.writeFileSync (fs.js:1265:35)
    at storeSet (/opt/IPFS Desktop/resources/app.asar/node_modules/countly-sdk-nodejs/lib/countly.js:1337:16)
    at toRequestQueue (/opt/IPFS Desktop/resources/app.asar/node_modules/countly-sdk-nodejs/lib/countly.js:985:13)
    at Timeout.heartBeat [as _onTimeout] (/opt/IPFS Desktop/resources/app.asar/node_modules/countly-sdk-nodejs/lib/countly.js:1007:17)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
Error: ENOENT, node_modules/countly-sdk-nodejs/data/__cly_event.json not found in /opt/IPFS Desktop/resources/app.asar
    at createError (electron/js2c/asar.js:111:17)
    at Object.func [as openSync] (electron/js2c/asar.js:146:27)
    at Object.writeFileSync (fs.js:1265:35)
    at storeSet (/opt/IPFS Desktop/resources/app.asar/node_modules/countly-sdk-nodejs/lib/countly.js:1337:16)
    at Timeout.heartBeat [as _onTimeout] (/opt/IPFS Desktop/resources/app.asar/node_modules/countly-sdk-nodejs/lib/countly.js:1014:13)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
Error: ENOENT, node_modules/countly-sdk-nodejs/data/__cly_queue.json not found in /opt/IPFS Desktop/resources/app.asar
    at createError (electron/js2c/asar.js:111:17)
    at Object.func [as openSync] (electron/js2c/asar.js:146:27)
    at Object.writeFileSync (fs.js:1265:35)
    at storeSet (/opt/IPFS Desktop/resources/app.asar/node_modules/countly-sdk-nodejs/lib/countly.js:1337:16)
    at /opt/IPFS Desktop/resources/app.asar/node_modules/countly-sdk-nodejs/lib/countly.js:1037:17
    at IncomingMessage.<anonymous> (/opt/IPFS Desktop/resources/app.asar/node_modules/countly-sdk-nodejs/lib/countly.js:1197:25)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Error: ENOENT, node_modules/countly-sdk-nodejs/data/__cly_queue.json not found in /opt/IPFS Desktop/resources/app.asar
    at createError (electron/js2c/asar.js:111:17)
    at Object.func [as openSync] (electron/js2c/asar.js:146:27)
    at Object.writeFileSync (fs.js:1265:35)
    at storeSet (/opt/IPFS Desktop/resources/app.asar/node_modules/countly-sdk-nodejs/lib/countly.js:1337:16)
    at /opt/IPFS Desktop/resources/app.asar/node_modules/countly-sdk-nodejs/lib/countly.js:1037:17
    at IncomingMessage.<anonymous> (/opt/IPFS Desktop/resources/app.asar/node_modules/countly-sdk-nodejs/lib/countly.js:1197:25)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
2020-04-29T19:11:52.440Z info: [web ui] window hidden
2020-04-29T19:11:57.659Z error: [web ui] crashed: [object Object]
Terminated
```

**Comment by danrobi11** [comment] 2020-04-30 00:31
I refered this issue to Galacteek because Galacteek wont connect to the network since ipfs-desktop update issue.

**Comment by lidel** [comment] 2020-04-30 12:07
I tested this on Debian 10 with empty profile and was unable to reproduce.
Sounds like problem specific to one user.

@danrobi11 quick feedback:

1. are you running go-ipfs manually, or letting ipfs-desktop take care of it? try shutting down everything, ipfs-desktop comes with go-ipfs inside.
2. if possible, start from scratch:
   - if you have important data in your repo (`~/.ipfs/`), back it up by compying to a safe locaiton before you remove anything
   - then remove everything with `rm -rf ~/.ipfs ~/.ipfs-desktop ~/.config/Electron ~/.config/IPFS\ Desktop`
   - kill all electron processes running in background: `killall electron`
     (you may have those if you miss tray icon)
   - start IPFS Desktop again
3. missing Tray icon is a know issue on some Linux distributions. We can't do anything about it, see potential workaround  for various linux desktops in [README#no-tray-icon-on-linux](https://github.com/ipfs-shipyard/ipfs-desktop/#no-tray-icon-on-linux)

Let us know if anything of this helped.

**Comment by pinnaculum** [comment] 2020-04-30 17:28
I've tried ipfs-desktop-0.11.1 with the AppImage and didn't have any issue. I had no preexisting ~/.ipfs-desktop.

**Comment by danrobi11** [comment] 2020-04-30 17:40
killall electron give me this:
electron: no process found
Even if ipfs-desktop is running I've: 'electron: no process found'  
Is this because im not running systemd?
@lidel  You might have tried to reproduce with debian 10 but debain 10 does run systemd and im not.
I installed 'xfce4-statusnotifier-plugin' and that fixed the systray issue, thx!
ipfs-desktop working now with Galacteek, thx!

**Comment by pinnaculum** [comment] 2020-04-30 17:48
This is most likely not related to systemd, i don't use systemd either

**Comment by lidel** [comment] 2020-04-30 19:46
@danrobi11 don't worry about `electron: no process found` is okay, it means there is no IPFS Desktop running in the background (we just wanted to be sure). It is not related to systemd in any way.

It sounds like `xfce4-statusnotifier-plugin`  solved your original problem, so I am closing this as fixed. Thank you for letting us know it helped!

**Closed by lidel** 2020-04-30 19:46 UTC
Labels: need/author-input, need/triage

**Comment by danrobi11** [comment] 2020-04-30 20:13
@lidel 'is okay, it means there is no IPFS Desktop running in the background'
No as I said above it gives me this result even tho ipfs-desktop is running
