### ISSUE TITLE
Could not toggle Ipfs command line tools

### ISSUE THREAD

**Issue by samuelandert** [ipfs-shipyard/ipfs-desktop#1219] opened 2019-10-27 12:25 UTC
I got an error, while trying to toggle the IPFS command line tool setting:

Please describe what you were doing when this error happened.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.9.7
- **Electron Version**: 6.0.12
- **Chrome Version**: 76.0.3809.146

**Error**

```
Error: Command failed: env ELECTRON_RUN_AS_NODE=1 "/Applications/IPFS Desktop.app/Contents/MacOS/IPFS Desktop" "/Applications/IPFS Desktop.app/Contents/Resources/app.asar/out/ipfs-on-path/scripts/install.js" --data="/Users/samuelandert/Library/Application Support/IPFS Desktop"
fs.js:126
    throw err

**Comment by rex4539** [comment] 2019-10-28 19:45
If you are on macOS 10.15 Catalina, it's probably a permissions issue. See also https://github.com/ipfs-shipyard/npm-on-ipfs/issues/119

**Comment by hacdias** [comment] 2019-10-28 21:13
@rex4539 thanks for helping out here. I doubt it's related to permissions, but it can be! This is not npm on ipfs, but the `ipfs` command line tool.

@samuelandert I also have Catalina and it works well here... what version do you have? Unfortunately, I don't have much info per the logs. I will see what I can do!

**Comment by samuelandert** [comment] 2019-11-01 09:34
@hacdias yes, I am on Catalina 10.15 
@rex4539 I tried the permissions, but it didn't changed anything.

**Comment by hacdias** [comment] 2019-11-13 08:42
@samuelandert this might seem stupid, but could you try running that command manually through the Terminal?

```
env ELECTRON_RUN_AS_NODE=1 "/Applications/IPFS Desktop.app/Contents/MacOS/IPFS Desktop" "/Applications/IPFS Desktop.app/Contents/Resources/app.asar/out/ipfs-on-path/scripts/install.js" --data="/Users/samuelandert/Library/Application Support/IPFS Desktop"
```

And show me the output please.

**Comment by hacdias** [comment] 2020-04-24 07:33
I'm closing this since we no longer got a reply from the author and I can't reproduce it on Catalina. However, if the issue persists, feel free to open a new issue.

**Closed by hacdias** 2020-04-24 07:33 UTC
Labels: kind/bug
