### ISSUE TITLE
can not start (npm start)

### ISSUE THREAD

**Issue by thimper** [ipfs-shipyard/ipfs-desktop#1276] opened 2019-12-05 02:14 UTC
> 2019-12-05T02:12:44.316Z info: [meta] logs can be found on /Users/macbookpro/Library/Application Support/Electron
(node:39733) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:39733) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
Countly initialized
2019-12-05T02:12:45.620Z info: [web ui] window ready
2019-12-05T02:12:45.621Z info: [tray] starting
2019-12-05T02:12:45.662Z info: [tray] started
2019-12-05T02:12:45.664Z error: (0 , _.default) is not a function
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ipfs-desktop@0.10.2 start:electron: `electron out/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ipfs-desktop@0.10.2 start:electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

>npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/macbookpro/.npm/_logs/2019-12-05T02_12_54_747Z-debug.log
ERROR: "start:electron" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ipfs-desktop@0.10.2 start: `cross-env NODE_ENV=development run-s build:babel start:electron`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ipfs-desktop@0.10.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by hacdias** [comment] 2020-04-24 07:37
Due to the lack of information and not being able to reproduce the error, I'm closing this. We're running `npm start` on the CI and on multiple Macs (I see you're using a mac too through the logs) and we have not had this problem. Please try running `npm ci` on the new master.

**Closed by hacdias** 2020-04-24 07:37 UTC
