### ISSUE TITLE
600 peers, all locations are unknown

### ISSUE THREAD

**Issue by da2x** [ipfs-shipyard/ipfs-desktop#774] opened 2018-12-26 13:55 UTC
Windows 10.1809, ipfs desktop 0.6.0

Every location is shown with a rainbow flag and “unknown”. I've currently got 600 peers.

The web UI does show locations for most peers.

**Comment by olizilla** [comment] 2019-01-02 14:57
Thanks for the heads up @da2x. The problem is in ipfs-geoip via ipfs-webui... https://github.com/ipfs/ipfs-geoip/issues/65

**Comment by olizilla** [comment] 2019-01-03 11:33
Fix for this is on it's way https://github.com/ipfs/ipfs-geoip/pull/66

**Comment by daviddias** [comment] 2019-01-03 12:22
@olizilla merged and released https://github.com/ipfs/ipfs-geoip/pull/66 for you :)

**Comment by daviddias** [comment] 2019-01-03 12:32
Thank you for fixing it! :)

**Closed** 2019-01-03 15:50 UTC
Labels: in progress
