### ISSUE TITLE
Tray Icon problems on Linux

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-desktop#1153] opened 2019-09-27 11:01 UTC
So, there are quite a few issues with people complaining they can't access the UI of IPFS Desktop on Linux. All of them are caused by the same reason: tray icons are being deprecated from many desktop environments and Electron has not yet worked out on a solution, nor it seems to be [happening soon](https://github.com/electron/electron/issues/10427).This affects all kinds of packages.

One possible way for us to circumvent this for now is to open the main Web UI window on Linux on startup. However, that will still leave the options of exiting desktop and other options provided by the menu behind.

I'm opening this in hope to gather feedback on how to create an workaround around this.

Please note that Linux support is **experimental** nonetheless.

**Comment by NatoBoram** [comment] 2019-09-27 21:50
Hm, not a fan of this solution.

Tray icons are an important feature. The desktops missing them are just deficient, intentionally or not, and regardless of their design philosophy.

A better solution would be to open a window when clicking on the application's launcher. That way, it now gains a behavior that's intuitive (clicking on a launcher generally launches the app) and it fixes the tray icon problem rather than creating a missing tray icon problem for other Linux users.

**Comment by olizilla** [comment] 2019-09-30 14:28
As a first step, we can have desktop open the webui window on launch as suggested. I'm not clear on how we can show the user that the app is still running if they close the window... what happens on others apps that are long running on desktops that dont have task tray icons?

**Comment by NatoBoram** [comment] 2019-09-30 17:56
> what happens on others apps that are long running on desktops that dont have task tray icons?

I don't know any long-running apps without tray icons except for command-line apps, but those don't even have desktop icons in the first place. For long-running apps *with* a tray icon on systems *without* a system tray, however, I've noticed a pattern.

* [Skype](https://www.skype.com/) launches its UI when clicking its icon even if it's already launched in background.
* [Discord](https://www.skype.com/) launches its UI when clicking its icon even if it's already launched in background.
* [Steam](https://store.steampowered.com/) launches its UI when clicking its icon even if it's already launched in background.
* [Chrome](https://www.google.com/chrome/) launches its UI when clicking its icon even if it's already launched in background.
* IPFS-Desktop doesn't react.

None of them closes on close. They minimize on minimize and go to system tray on close.

One problem that may arise is that options in the tray app will be hidden. This can be fixed by having them accessible from inside the app as well.

**Comment by hacdias** [comment] 2019-10-07 06:55
> ...we can have desktop open the webui window on launch as suggested.

I absolutely agree, but we should do that only on Linux perhaps. And even there some issues might arise... What about those users who have IPFS Desktop setup to start up automatically when they turn on the computer? I doubt anyone wants a window to be open in those cases.

I can investigate to see if there's any way to know if the app is being launched by a startup mechanism or not.

**Comment by Lazerbeak12345** [comment] 2019-11-15 20:53
I like your idea about doing that on only Linux @hacdias, but perhaps we should be even more specific. On the default KDE layout, for example, it has a system tray, and it works perfectly, however, on Gnome, there seems to be no tray whatsoever.

**Comment by lidel** [comment] 2020-03-09 21:08
Note to self: Tray support on modern linux DE is severely broken.  
Pure saddness: https://github.com/electron/electron/issues/21445

**Comment by vladimiry** [comment] 2020-03-10 07:29
> Electron 8 switched to it,

@chromium did and Electron v8 took it as a given thing.

**Comment by dotenorio** [comment] 2020-04-02 19:35
See my solution:

https://github.com/zulip/zulip-desktop/issues/910#issuecomment-608056150

**Comment by lidel** [comment] 2020-04-17 21:24
@dotenorio I am afraid the code you linked is a fix for other issue. It does not solve the mess of  Electron 8 switching to  `StatusNotifier` and breaking Tray icon in various Linux setups as noted in https://github.com/electron/electron/issues/21445#issuecomment-565061274.

**Comment by lidel** [comment] 2020-04-17 23:04
For testing purposes, I was able to get tray icon back on `i3bar` 
 with https://git.sr.ht/~steef/snixembed (a StatusNotifier→XEmbed proxy)

**Comment by lidel** [comment] 2020-04-19 23:32
@hacdias the screenshot of Lungo app you posted in the other issue inspired me to come up with a potential workaround for Linux for next 10 years (until everyone switch to  `StatusNotifier` :upside_down_face:):

> ![2020-04-20--01-24-34](https://user-images.githubusercontent.com/157609/79702521-bcfaf700-82a5-11ea-894a-3202342c1ae7.png)


Idea: 
What if we add "Show WebUI at Launch" feature to ipfs-desktop and enable it by default on Linux?

Rationale: 
- if user does not have the tray icon in Linux DE
  - clicking ipfs icon is "Applications" would start node and show webui
  - closing webui would keep daemon running
  - clicking "IPFS Desktop" in "Applications" again would show webui
  - downside: no controls for stopping node, but its better than clicking on icon and nothing happening
- if user has the tray icon in their Linux DE and does not want webui to show on startup, they can disable it with one click

**Comment by vladimiry** [comment] 2020-04-20 04:20
> What if we add "Show WebUI at Launch" feature to ipfs-desktop and enable it by default on Linux?

I ended up with this scenario for Linux users of ElectronMail ([ref1](https://github.com/vladimiry/ElectronMail/issues/254), [ref2](https://github.com/electron/electron/issues/21445#issuecomment-565061274)).

**Comment by lidel** [comment] 2020-05-26 21:38
Thanks for heads up [in the original issue](https://github.com/electron/electron/issues/21445#issuecomment-634163402) @vladimiry! 

> To whom it may concern. It turned out Electron is getting rid of DBus related tray icon implementation rolled out with chromium update in Electron v8 in favor of previously used / `GTK/appindicator` approach, see https://github.com/electron/electron/pull/23674.

Let's reopen this and track progress in https://github.com/electron/electron/pull/23674 – if they indeed restore old tray support, that would be great news for our Linux users.

**Comment by lidel** [comment] 2020-07-31 13:49
https://github.com/electron/electron/pull/23674 got merged and backported to 8.x: https://github.com/electron/electron/pull/23674#issuecomment-637876725

It seems to be the [lesser evil](https://github.com/electron/electron/pull/23674#issuecomment-639304297).

@rafaelramalho19 I believe upgrading to electron [v8.4.1](https://github.com/electron/electron/releases/tag/v8.4.1) should include the above "fix". Sooner we switch, the sooner we identify any UX regressions caused by it on various Linuxes.

**Comment by mPiotrek** [comment] 2020-08-01 14:11
> * `Cinnamon / Mint`: `"System Settings" -> "General" -> "Enable support for indicators"` flag needs to be enabled. Some issues still possible, see [linuxmint/cinnamon#9176](https://github.com/linuxmint/cinnamon/issues/9176).

@lidel Some time ago Cinnamon implemented this differently and that "support for indicators" option is now gone from the settings.
(see https://github.com/linuxmint/cinnamon/commit/eb7f2235debcd3baf36d2d94a23465158b8bdafc)
Since your [comment](https://github.com/ipfs-shipyard/ipfs-desktop/issues/1153#issuecomment-596780147) is linked from the [readme](https://github.com/ipfs-shipyard/ipfs-desktop/blob/master/README.md), it would be nice to update that it just works.

**Comment by lidel** [comment] 2020-09-14 19:59
Heads up: we are planning to switch to Electron 9 in the next release, and it will include change described in https://github.com/ipfs-shipyard/ipfs-desktop/issues/1153#issuecomment-634293717

**Comment by lidel** [comment] 2020-10-05 16:58
@bertrandfalguiere thank you for testing across different distros in https://github.com/ipfs-shipyard/ipfs-desktop/issues/1661 :heart: 
Do you know how does the tray icon behave now? Which desktop environment were you using for tests?

**Comment by bertrandfalguiere** [comment] 2020-10-06 08:01
@lidel The tray icon behave nominally now on my system with v0.13.0 :). 
I tested with Ubuntu 20.04. I don't know which app indicator I'm using. I think the default one, which should be Gnome Shell?
I haven't tested on other distros (and probably won't).

**Comment by lidel** [comment] 2020-10-06 12:05
@bertrandfalguiere that is enough, thank you! I was mostly worried about Ubuntu, as historically they used custom stuff and hid tray indicators. Seems that Electron 9.x correctly supports whatever Ubuntu uses these days, so all good :+1:

**Comment by lidel** [comment] 2020-10-07 19:00
I believe this should be fixed in [v0.13](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.13.0), but please reopen if you experience any tray problems (include info about your distro and DE/WM/tray setup)

**Closed by lidel** 2020-10-07 19:00 UTC
Labels: P1, area/linux, kind/bug, kind/maintenance, need/analysis, status/in-progress

**Comment by teohhanhui** [comment] 2021-09-26 13:47
There really should be a way to use IPFS Desktop **without** any tray icon.

For example, GNOME by default does not include any appindicator support, and as a user that's not something I'd change.

**Comment by teohhanhui** [comment] 2021-09-28 11:24
GNOME did it for good reason: https://blogs.gnome.org/aday/2017/08/31/status-icons-and-gnome/

Anyway, the reality is that it's highly unlikely for appindicator or similar to be supported by default: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/1014

So app developers should provide a way to use the app without tray icon. It's not that hard. Many other apps have done it.

**Comment by lidel** [comment] 2021-09-28 23:05
@teohhanhui do you have examples of some apps that do it "correctly"? Would be really useful to study their behavior and implement something similar.

**Comment by teohhanhui** [comment] 2021-09-29 16:29
Discord, for example.

![Screenshot from 2021-09-30 00-26-20](https://user-images.githubusercontent.com/548843/135310114-1f00712e-75ed-4ac4-9013-94a4a5bfccca.png)

Use of the tray icon should be entirely optional. Relevant items from the tray menu can be duplicated in an in-app menu.

**Comment by NatoBoram** [comment] 2021-09-29 21:10
> Do you have examples of some apps that do it "correctly"? Would be really useful to study their behavior and implement something similar.

Just to make sure, @lidel, are you asking for [this list](https://github.com/ipfs/ipfs-desktop/issues/1153#issuecomment-536676760) again?

> > what happens on others apps that are long running on desktops that dont have task tray icons?
> 
> I don't know any long-running apps without tray icons except for command-line apps, but those don't even have desktop icons in the first place. For long-running apps _with_ a tray icon on systems _without_ a system tray, however, I've noticed a pattern.
> 
> * [Skype](https://www.skype.com/) launches its UI when clicking its icon even if it's already launched in background.
> * [Discord](https://www.skype.com/) launches its UI when clicking its icon even if it's already launched in background.
> * [Steam](https://store.steampowered.com/) launches its UI when clicking its icon even if it's already launched in background.
> * [Chrome](https://www.google.com/chrome/) launches its UI when clicking its icon even if it's already launched in background.
> * [qBitTorrent](https://www.qbittorrent.org/) launches its UI when clicking its icon even if it's already launched in background.
> * [Teams](https://teams.microsoft.com/) launches its UI when clicking its icon even if it's already launched in background.
> * [MSI Afterburner](https://www.msi.com/page/afterburner) launches its UI when clicking its icon even if it's already launched in background.
> * [GeForce Experience](https://www.nvidia.com/en-us/geforce/geforce-experience/) launches its UI when clicking its icon even if it's already launched in background.
> * IPFS-Desktop doesn't react.
> 
> None of them closes on close. They minimize on minimize and go to system tray on close.
> 
> One problem that may arise is that options in the tray app will be hidden. This can be fixed by having them accessible from inside the app as well.

**Comment by vladimiry** [comment] 2021-09-29 21:27
> launches its UI when clicking its icon even if it's already launched in background.

For example in https://github.com/vladimiry/ElectronMail when it's already started and you launch its binary/shortcut again it will open/activate the window of already executed app instance. Some users bind the binary execution to a hotkey and so they use the hotkey to unhide the app from the tray (from the hidden state if there is no tray).

> None of them closes on close. They minimize on minimize and go to system tray on close.

Pretty regular behavior on Windows systems. It's good though if there is an option to make the window close action close the app.

> This can be fixed by having them accessible from inside the app as well.

This is how it's done in ElectronMail.
