### ISSUE TITLE
After last update IPFS-Desktop fails duet macOS signature virification

### ISSUE THREAD

**Issue by Gozala** [ipfs-shipyard/ipfs-desktop#1474] opened 2020-04-30 00:16 UTC
**Describe the bug**

**To Reproduce**
1. Restart IPFS Desktop after seeing an upgrade message.

**Expected behavior**
IPFS Desktop should not fail after it updated itself, or for the very least it should provide some actionable instruction to the user.

**Screenshots**

<img width="488" alt="image" src="https://user-images.githubusercontent.com/21236/80659050-a9d1ef00-8a3c-11ea-9157-f9e6194ee98c.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Version: Presumably whatever the last update was

**Additional context**

**Comment by Gozala** [comment] 2020-04-30 00:20
<img width="251" alt="image" src="https://user-images.githubusercontent.com/21236/80659396-b86cd600-8a3d-11ea-8076-80adc2760f9b.png">

Version it updated to

**Comment by Gozala** [comment] 2020-04-30 00:24
Still seem to work, I assume `fs-repo-migrations` was supposed to migrate the repo and failed due to apple's `about com.apple.quarantine` xattr. Not sure where that binary is nor I see the same error on restarting the IPFS Desktop.

**Comment by hacdias** [comment] 2020-04-30 07:09
"FirefoxNighty.app downloaded this file on **June 12, 2017**" are you sure this was caused by IPFS Desktop? Multiple people on macOS Catalina tried it out and no one had an error.

It seems to be trying to execute something downloaded in 2017, which sounds fishy. Did you haver install that binary on your system? Can you try `where fs-repo-migrations`?

I'm not sure about the behaviour of `go-ipfs` in relation of that binary.

/cc @lidel

**Comment by lidel** [comment] 2020-04-30 20:01
I don't believe `fs-repo-migrations` is shipped with Desktop, but I think I know why that old binary was called when you restarted the app.

`go-ipfs` shipped with Desktop app is run with `--migrate` for seamless repo migrations. With that parameter, go-ipfs checks if `fs-repo-migrations` is on `PATH`, and if not, downloads it:

https://github.com/ipfs/go-ipfs/blob/v0.5.0/repo/fsrepo/migrations/migrations.go#L40

Sounds like you had an older version on your path, which you manually downloaded in 2017, and that metadata caused macOS Catalina to show this error.

@Gozala I believe the fix here is to remove old `fs-repo-migrations` – can you confirm if it removed the error?

cc @Stebalien to be aware lack of notarization of `fs-repo-migrations` may be a problem if people downloaded them manually in past.

**Comment by Stebalien** [comment] 2020-04-30 22:01
@lidel can we notarize those old fs-repo-migrations binaries?

**Comment by Stebalien** [comment] 2020-04-30 22:02
That is, write a script to notarize everything in dist.ipfs.io?

**Comment by Stebalien** [comment] 2020-04-30 22:02
Actually, can we do this in CI somewhere?

**Comment by lidel** [comment] 2020-05-04 15:46
@Stebalien non-Electron projects should be able to use https://github.com/mitchellh/gon
Someone familiar with macOS can run it locally (gon must be run on a macOS machine with XCode 11.0 or later) to manually notarize old binaries or set up it in CI to run on mac worker. 

Caveats:
- notarization stappling changes the `.dmg` – not sure how it works when standalone binary is notarized 
  - for old stuff, to keep binaries and hashes intact, we may ignore stappled bianry and only rely on online notarization (requires pinging apple servers, but better than nothing/error)
  - for new stuff notarization with stappling needs to happen before checksums/cids are calculated for dist.ipfs.io manifests
- when set up at CI, ensure secrets are safe (eg. exposing them only on release branch).

**Comment by Gozala** [comment] 2020-05-04 20:30
> go-ipfs shipped with Desktop app is run with --migrate for seamless repo migrations. With that parameter, go-ipfs checks if fs-repo-migrations is on PATH, and if not, downloads it:
>
> Sounds like you had an older version on your path, which you manually downloaded in 2017, and that metadata caused macOS Catalina to show this error. (macOS started requiring notarization recently for things downloaded with a web browser, but using `wget` or `curl` should be fine)

Indeed

```
xattr -v $(which fs-repo-migrations)                                                                                                         
/Users/gozala/.local/bin/fs-repo-migrations: com.apple.quarantine
```

> @Gozala I believe the fix here is to remove old `fs-repo-migrations` – can you confirm if it removed the error?

I can't confirm it fixes that as that error has not occurred ever since that last time. I assume macOS prompts user with that message only once & fails silently on subsequent runs.

**Comment by lidel** [comment] 2020-05-05 12:50
Ok, I was not able to reproduce with "implicit" repo migraiton. I believe it is safe to say this does not impact regular users of ipfs-desktop, nor is caused by the app itself – closing.

(macOS notarization of commandline tools at dist.ipfs.io needs to be solved upstream)

**Closed by lidel** 2020-05-05 12:50 UTC
Labels: need/analysis, need/author-input, need/triage
