### ISSUE TITLE
Crash on computer restart

### ISSUE THREAD

**Issue by balupton** [ipfs-shipyard/ipfs-desktop#823] opened 2019-02-12 14:44 UTC
Please describe what you were doing when this error happened.

Restarted my computer. After login, there was a dialog reporting the following crash:

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.6.1
- **Electron Version**: 4.0.0
- **Chrome Version**: 69.0.3497.106

**Error**

```
Error: net::ERR_NETWORK_CHANGED
    at GitHubProvider.getLatestVersion (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/providers/GitHubProvider.ts:39:25)
    at /Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:347:26
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at MacUpdater.getUpdateInfoAndProvider (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:336:43)
    at /Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.doCheckForUpdates (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
    at MacUpdater.checkForUpdates (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at MacUpdater.checkForUpdatesAndNotify (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:249:41)
    at _callee$ (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/out/index.js:52:44)
    at tryCatch (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at /Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
    at _checkUpdates (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/out/index.js:64:24)
    at checkUpdates (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/out/index.js:38:24)
    at _callee2$ (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/out/index.js:96:13)
    at tryCatch (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
```

**Comment by hacdias** [comment] 2019-02-13 14:13
I'm closing this one as duplicate of #792

**Closed by hacdias** 2019-02-13 14:13 UTC
