### ISSUE TITLE
ipfs-desktop failed to start

### ISSUE THREAD

**Issue by shubhamvaity** [ipfs-shipyard/ipfs-desktop#1051] opened 2019-08-23 05:32 UTC
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.8.0
- **Electron Version**: 5.0.2
- **Chrome Version**: 73.0.3683.121

**Error**

```
Error: Command failed: powershell.exe -nop -exec bypass -win hidden C:\Users\Shubham Vaity\AppData\Local\Programs\ipfs-desktop\resources\app.asar.unpacked\out\late\ipfs-on-path\scripts\install.ps1
Program 'Shubham' failed to run: No application is associated with the specified file for this operationAt line:1 
char:1
  C:\Users\Shubham Vaity\AppData\Local\Programs\ipfs-desktop\resources\ ...
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
  C:\Users\Shubham Vaity\AppData\Local\Programs\ipfs-desktop\resources\ ...
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
      FullyQualifiedErrorId : NativeCommandFailed
 

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:194:13)
    at maybeClose (internal/child_process.js:998:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

**Comment by hacdias** [comment] 2019-08-25 08:27
Duplicate of #964.

**Closed by hacdias** 2019-08-25 08:27 UTC
