### ISSUE TITLE
IPFS Desktop stuck on "IPFS is Starting"

### ISSUE THREAD

**Issue by jjv360** [ipfs-shipyard/ipfs-desktop#1723] opened 2020-12-29 11:27 UTC
It never gets past IPFS is Starting for me, unless I run `ipfs daemon` in a terminal window first...

This error also happens when pressing Check for Updates, while in this "IPFS is Starting" stuck state...

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.13.2
- **Electron Version**: 9.3.2
- **Chrome Version**: 83.0.4103.122

**Error**

```
TypeError: ctx.manualCheckForUpdates is not a function
    at click (C:\Users\jjv36\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\tray.js:198:30)
    at MenuItem.click (electron/js2c/browser_init.js:65:1624)
    at Function.executeCommand (electron/js2c/browser_init.js:73:1102)
```

**Comment by jessicaschilling** [comment] 2020-12-29 15:04
Thank you for reporting this. The core team is temporarily in a minimal state due to winter holidays but will add to triage upon return - in the meantime you may also wish to repost to https://discuss.ipfs.io/ for community support.

**Comment by jessicaschilling** [comment] 2020-12-29 15:06
Thank you for reporting this. The core team is temporarily in a minimal state due to winter holidays but will add to triage upon return - in the meantime you may also wish to repost to https://discuss.ipfs.io/ for community support. 

Question: Did you originally install Desktop for all users of this machine? Are you running as a different user than the one that installed Desktop?

**Comment by jjv360** [comment] 2020-12-29 19:53
> Question: Did you originally install Desktop for all users of this machine? Are you running as a different user than the one that installed Desktop?

I installed it via chocolatey, so I'm not sure if it's installed for all users or not... My machine only has one user on it though.

**Comment by jessicaschilling** [comment] 2021-01-04 19:06
@rafaelramalho19 - are you able to investigate further on your Windows machine? Thank you.

**Comment by rafaelramalho19** [comment] 2021-01-11 19:41
@jjv360 I installed ipfs-desktop through chocolatey and it works fine, I tried multiple aways to downgrade and upgrade to try and reproduce your error but I'm unable to.

Would you mind trying a fresh install of ipfs-desktop and see if that helps?

**Comment by NorseGaud** [comment] 2021-01-14 21:51
Having this happen on macOS using brew install --cask ipfs

**Comment by NorseGaud** [comment] 2021-01-14 21:54
Confirmed it's also the case with the DMG installer.

**Comment by lidel** [comment] 2021-01-14 22:03
@jjv360 @NorseGaud  sadly we are unable to reproduce, need more information.

Did you do any of below by any chance?

- Set custom `IPFS_PATH` anywhere? 
- Moved your repo to different location than the default?

If possible:
1. From the "IPFS icon" menu in your menubar/system tray, go to `Advanced` → `Open Logs Directory`
2. Find `*.log` files
3. Attach `error.log` and `combined.log` to this issue.

**Comment by NorseGaud** [comment] 2021-01-14 22:05
[combined.log](https://github.com/ipfs-shipyard/ipfs-desktop/files/5817224/combined.log)

error.log is empty

This is my first time ever looking at IPFS, so I haven't changes anything from defaults :)

**Comment by NorseGaud** [comment] 2021-01-14 22:13
Just got this: 
<img width="1439" alt="Screen Shot 2021-01-14 at 5 13 20 PM" src="https://user-images.githubusercontent.com/5896030/104655568-e22d6200-568b-11eb-82e6-ac3a371e114d.png">

**Comment by lidel** [comment] 2021-01-14 22:22
Sadly Desktop logs did not help. 

@NorseGaud  Are you able to Quit IPFS Desktop and then start it in terminal, to see if there is any output from go-ipfs daemon that does not end up in logs? I suspect there is an issue related to daemon startup.

Not sure how to do it (not a macOS user),  perhaps something like:

```
open -a IPFS\ Desktop
```

You should see startup + then logs from go-ipfs similar to this:

```
2021-01-14T22:20:36.516Z info: [meta] logs can be found on /home/lidel/.config/IPFS Desktop
2021-01-14T22:20:37.479Z info: [web ui] window ready
2021-01-14T22:20:37.479Z info: [web ui] navigate to /
2021-01-14T22:20:37.499Z info: [tray] starting
2021-01-14T22:20:37.566Z info: [tray] started
2021-01-14T22:20:37.567Z info: [ipfsd] start daemon STARTED
2021-01-14T22:20:37.806Z error: [ipfsd] start daemon Error: Initializing daemon...
go-ipfs version: 0.7.0
Repo version: 10
System version: amd64/linux
Golang version: go1.14.4
(→ interesting stuff  here)
```

**Comment by NorseGaud** [comment] 2021-01-14 22:25
Yep, actually was already trying that:

```
❯ ipfs daemon
Initializing daemon...
go-ipfs version: 0.7.0-ea77213
Repo version: 10
System version: amd64/darwin
Golang version: go1.14.12
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/127.0.0.1/udp/4001/quic
Swarm listening on /ip4/192.168.0.107/tcp/4001
Swarm listening on /ip4/192.168.0.107/udp/4001/quic
Swarm listening on /ip4/192.168.64.1/tcp/4001
Swarm listening on /ip4/192.168.64.1/udp/4001/quic
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /ip6/::1/udp/4001/quic
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/127.0.0.1/udp/4001/quic
Swarm announcing /ip4/192.168.64.1/tcp/4001
Swarm announcing /ip4/192.168.64.1/udp/4001/quic
Swarm announcing /ip4/24.62.29.132/tcp/4001
Swarm announcing /ip4/24.62.29.132/udp/4001/quic
Swarm announcing /ip6/::1/tcp/4001
Swarm announcing /ip6/::1/udp/4001/quic
```

I see that STDOUT, but I can't access the webui at localhost:5001/webui.

```
❯ netstat -vanp tcp | grep 5001
tcp6       0      0  ::1.5001               ::1.55935              ESTABLISHED 407252 146808    730      0 0x0082 0x00000004
tcp6       0      0  ::1.55935              ::1.5001               ESTABLISHED 407800 146808  41206      0 0x0102 0x00000008
tcp6       0      0  ::1.5001               *.*                    LISTEN      131072 131072    730      0 0x0080 0x00000006
tcp4       0      0  127.0.0.1.5001         *.*                    LISTEN      131072 131072    730      0 0x0080 0x00000006
tcp6       0      0  ::1.55912              ::1.5001               TIME_WAIT   407800 146808  41206      0 0x2131 0x00000008

❯  lsof -i tcp:5001
COMMAND     PID         USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Brave\x20 41206 nathanpierce   42u  IPv6 0x9c1258feff4e2257      0t0  TCP localhost:55935->localhost:commplex-link (ESTABLISHED)
```

**Comment by NorseGaud** [comment] 2021-01-14 22:27
Oh, it actually looks like ipfs daemon is stuck...
I never see the 
```
> API server listening on /ip4/127.0.0.1/tcp/5001
> Gateway server listening on /ip4/127.0.0.1/tcp/8080
``
which is what the docs say I should see

**Comment by NorseGaud** [comment] 2021-01-15 14:22
Moving my comments to https://github.com/ipfs-shipyard/ipfs-desktop/issues/1730

**Comment by jessicaschilling** [comment] 2021-01-19 23:22
@jjv360 - per @rafaelramalho19's comment above, would you mind trying a fresh install of ipfs-desktop and see if that helps?

**Comment by jessicaschilling** [comment] 2021-01-19 23:41
Note that https://github.com/ipfs-shipyard/ipfs-desktop/issues/1734 is a duplicate error under Windows.

**Comment by jjv360** [comment] 2021-01-22 07:20
Sorry for the delay! I have uninstalled ipfs-desktop via chocolatey and installed 0.13.2, 0.13.1, 0.13.0 versions manually and they all get stuck the same way. I don't have a IPFS_PATH environment variable set. I deleted the logs and then started the app again, and when it got stuck error.log was empty, and combined.log showed this:

```
2021-01-22T07:14:41.405Z info: [meta] logs can be found on C:\Users\jjv36\AppData\Roaming\IPFS Desktop
2021-01-22T07:14:42.037Z info: [web ui] window ready
2021-01-22T07:14:42.037Z info: [tray] starting
2021-01-22T07:14:42.134Z info: [tray] started
2021-01-22T07:14:42.134Z info: [ipfsd] start daemon STARTED
```

Pressing "Check for Updates" still crashes with that `ctx.manualCheckForUpdates is not a function` error as well.

**Comment by rafaelramalho19** [comment] 2021-01-22 13:46
The `Pressing "Check for Updates" still crashes with that ctx.manualCheckForUpdates is not a function error as well.` part sounds especially weird, since I'm able to click the button in both my windows machines without any errors.

Also looking at the codebase there shouldn't really be an issue with the manual check for updates...

Are you able to provide us with your configuration file? 
![image](https://user-images.githubusercontent.com/24696635/105498442-1fab7400-5cb8-11eb-931b-396b6c0112fb.png)


And also check your version in system tray to be 100% sure you're running ipfs-desktop@0.13.2 ? 
![image](https://user-images.githubusercontent.com/24696635/105498520-35b93480-5cb8-11eb-9c5d-8614196ee685.png)

**Comment by jjv360** [comment] 2021-01-23 07:59
I've tried the same install process (via chocolatey) on a virtual machine and it worked fine, so it's definitely something wrong on my machine only...

However I did notice that if you click Check for Updates during the 5 or so seconds that "IPFS is Starting" you do get the same crash.

Is there a way to see the full commandline to ipfs.exe that IPFS Desktop is trying to run? Then I can try run it manually... I don't even see ipfs.exe in task manager while it's in this state. I tried running this but it worked fine:

```
"C:\Users\jjv36\AppData\Local\Programs\IPFS Desktop\resources\app.asar.unpacked\node_modules\go-ipfs\go-ipfs\ipfs.exe" daemon --migrate --enable-gc --routing dhtclient
```

Here's my versions:
<img width="286" alt="version" src="https://user-images.githubusercontent.com/2771104/105572480-0cec7a00-5d60-11eb-9a00-f0e60c4e01aa.png">

And here's my config (which I haven't changed):

```js
{
	"ipfsConfig": {
		"type": "go",
		"path": "C:\\Users\\jjv36\\.ipfs",
		"flags": [
			"--migrate",
			"--enable-gc",
			"--routing",
			"dhtclient"
		],
		"keysize": 2048
	},
	"language": "en-US",
	"experiments": {
		"npmOnIpfs": false
	},
	"__internal__": {
		"migrations": {
			"version": "6.0.0"
		}
	},
	"openWebUIAtLaunch": false,
	"daemonConfigRevision": 1,
	"checkedCorsConfig": true,
	"window": {
		"width": 1441,
		"height": 901
	},
	"ipfsOnPath": false
}
```

**Comment by jjv360** [comment] 2021-01-23 08:07
I just noticed `ipfsOnPath` was `false` on my own machine but `true` on the virtual machine... I changed it to `true` on my own machine but it made no difference...

**Comment by UnKnoWn-Consortium** [comment] 2021-01-23 13:39
I have encountered the same issue. The desktop app stuck at the starting loop unless I manually start an IPFS daemon at CLI. It appears the desktop app fails to invoke and spawn an ipfs.exe binary. 

I have cloned the repo and tried to see if the app has failed to locate the binary. The answer is negative. The app does successfully locate the bundled binary. My current bet is that the `ipfsd-ctl` package somehow fails to spawn the daemon at my system. Still investigating.

**Comment by UnKnoWn-Consortium** [comment] 2021-01-23 13:46
> The `Pressing "Check for Updates" still crashes with that ctx.manualCheckForUpdates is not a function error as well.` part sounds especially weird, since I'm able to click the button in both my windows machines without any errors.
> 
> Also looking at the codebase there shouldn't really be an issue with the manual check for updates...

https://github.com/ipfs-shipyard/ipfs-desktop/blob/6dbfa13bfa0f80c490696818bbb5c4c42aeb22fe/src/index.js#L72
https://github.com/ipfs-shipyard/ipfs-desktop/blob/6dbfa13bfa0f80c490696818bbb5c4c42aeb22fe/src/index.js#L73

The startup process is stuck at the `setupDaemon` right before `setupAutoUpdater`. The method `manualCheckForUpdates` is exactly defined at `setupAutoUpdater`. So I guess it is not that weird.

**Comment by UnKnoWn-Consortium** [comment] 2021-01-23 19:20
Okay further investigation suggests it is a rather complicated matters as there are a couple of things interleaving with each other... 

Before the `start` method of the `ipfsd-ctl` controller instance is called, a `checkPorts` function is called to determine if the ports required by ipfs are available. 

https://github.com/ipfs-shipyard/ipfs-desktop/blob/6dbfa13bfa0f80c490696818bbb5c4c42aeb22fe/src/daemon/daemon.js#L72-L75

Things was first stuck at this `checkPorts` function defined at config.js. 

https://github.com/ipfs-shipyard/ipfs-desktop/blob/6dbfa13bfa0f80c490696818bbb5c4c42aeb22fe/src/daemon/config.js#L216-L231

The culprit is the `checkIfAddrIsDaemon` function. What it does is to make a POST request to the previously identified API address (which is usually 127.0.0.1:5001) with a specific path `/api/v0/refs?arg=/ipfs/QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn` and see if there is a daemon already running that would reply with 200. Simple but not so elegant. 

https://github.com/ipfs-shipyard/ipfs-desktop/blob/6dbfa13bfa0f80c490696818bbb5c4c42aeb22fe/src/daemon/config.js#L156-L175

The request has no timeout explicitly set. There is supposed to be a default timeout value of 120,000ms (i.e. 2 minutes) in Node 12.14.1 that comes with Electron 9 where the request can resort to (P.S. This default value was dropped in Node 13. So it is no longer the case in Electron 10 which comes with Node 14. See: https://github.com/nodejs/node/pull/27558). 

If there happens to be any service **other than ipfs** that listens to the API port (5001) but not replying to the request (properly a la HTTP). It should take the whole 2 minutes before the request timing out. But in my case the promise never gets resolved. So the startup process is stuck there. 

So I tried to get this fixed by adding back the timeout property at the request option and the listener for timeout event. But this is not the end. Continue next.

**Comment by UnKnoWn-Consortium** [comment] 2021-01-23 20:11
Okay. Now, with the `checkIfAddrIsDaemon` finally resolving, the program proceeds and it determines that my setup needs an alternative port and offers me 5002 in the following prompt which is the expected behavior. 

![2021-01-24_032117](https://user-images.githubusercontent.com/9733856/105611903-43270980-5df3-11eb-82f9-d8a6b6b9f5b4.png)

I clicked the "Use port 5002 instead". But the app is still stuck at the startup process. So our journey continues... 

This time the process is stuck at the `start` method of the `ipfsd-ctl` controller. 

https://github.com/ipfs/js-ipfsd-ctl/blob/85229f5b5f8e2d3c2676ca2ceb77cb4163627a6d/src/ipfsd-daemon.js#L181-L188

The method first invokes a `checkForRunningApi` function which is essentially a `fs.readFileSync` of the file `api` in the .ipfs folder. The file contains only one line and in my case it is "/ip4/127.0.0.1/tcp/5001". As the file is not empty, the method continues and calls two "private" methods `_setApi` and `_createApi`. This is the second culprit of the issue. I have accepted the alternative port (from 5001 to 5002) above but the file from which the `ipfsd-ctl` controller reads the api is not updated.

**Comment by UnKnoWn-Consortium** [comment] 2021-01-23 20:21
@jjv360 I think you can try checking if the port 5001 is occupied by other application. If yes, maybe you can try changing the `config` and `api` file in .ipfs folder at your home folder and see if it works. Good luck.

**Comment by jjv360** [comment] 2021-01-24 10:22
> @jjv360 I think you can try checking if the port 5001 is occupied by other application. If yes, maybe you can try changing the `config` and `api` file in .ipfs folder at your home folder and see if it works. Good luck.

Yes, thank you so much! I have AirServer running which also uses port 5001, if I close that then IPFS Desktop starts without any issues. I changed those files to port `5005` and now I can run both apps at the same time as well.

I did have to change IPFS Companion's settings to that port as well (the Chrome extension) but it seems to be working fine...

**Closed** 2021-01-25 15:27 UTC
Labels: need/author-input

**Comment by UnKnoWn-Consortium** [comment] 2021-01-25 19:14
@jessicaschilling I think you had better take a look at the two issues I identified. Otherwise they will keep coming back and haunt other users. They are specifically: 
1. Promise returned by `checkIfAddrIsDaemon` function at `config.js` does not resolve when the target address is occupied by another service that may or may not be responding to the test POST request; and
2. Selecting an alternative port via the prompt presented by the app does not alter the `api` file inside the `.ipfs` folder

Thanks.

**Comment by jessicaschilling** [comment] 2021-01-25 19:31
Apologies - you got there before I did. Thanks for the tidy summarization. Issue is https://github.com/ipfs-shipyard/ipfs-desktop/issues/1749.
