### ISSUE TITLE
Tried to Install the latest update without removing the old version.

### ISSUE THREAD

**Issue by sigmaintegrale** [ipfs-shipyard/ipfs-desktop#1297] opened 2019-12-20 04:34 UTC
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.9.5
- **Electron Version**: 6.0.11
- **Chrome Version**: 76.0.3809.146

**Error**

```
Error: Object has been destroyed
    at Object.ctx.launchWebUI (C:\Users\Sigma_Int_03\AppData\Local\Programs\ipfs-desktop\resources\app.asar\out\webui\index.js:120:24)
    at _callee$ (C:\Users\Sigma_Int_03\AppData\Local\Programs\ipfs-desktop\resources\app.asar\out\second-instance.js:66:29)
    at tryCatch (C:\Users\Sigma_Int_03\AppData\Local\Programs\ipfs-desktop\resources\app.asar\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\Sigma_Int_03\AppData\Local\Programs\ipfs-desktop\resources\app.asar\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (C:\Users\Sigma_Int_03\AppData\Local\Programs\ipfs-desktop\resources\app.asar\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\Sigma_Int_03\AppData\Local\Programs\ipfs-desktop\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Sigma_Int_03\AppData\Local\Programs\ipfs-desktop\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
```

**Comment by hacdias** [comment] 2019-12-20 12:46
@sigmaintegrale the latest version is 0.10.2: https://github.com/ipfs-shipyard/ipfs-desktop/releases ad not 0.9.5. Would you mind to update, please?

**Comment by hacdias** [comment] 2020-04-24 07:38
Closing this since it's related to an old version and probably was fixed in the meanwhile. Can't reproduce this on Windows either.

**Closed by hacdias** 2020-04-24 07:38 UTC
